### ISSUE TITLE
import pro.truongsinh.appium_flutter.FlutterFinder; - Maven repo is not available

### ISSUE THREAD

**Issue by obula01** [appium/appium-flutter-driver#416]
Hi,

I am trying to java examples for the below classes. But i am not able to find maven repositery for this. class

https://github.com/appium-userland/appium-flutter-driver/tree/main/example/java/src/test/java/example/appium

import pro.truongsinh.appium_flutter.FlutterFinder - Maven repo not available.

Can you please let me know how to resolve this

**Comment by Higgens75** [comment]
also never found a public package for java/kotlin classes.
I have build it myself locally and made a local maven repo.

**Comment by obula01** [comment]
Hi @Higgens75 

I have got jar file from the below link.
https://github.com/truongsinh/appium-flutter-driver/files/3541350/repository.zip

But now i am getting nullPointer exception after executing my program. Below is my code

**Code:**

@Test
    public void test() throws InterruptedException {
    	Thread.sleep(6000);
    	clickToElement("Check-In");
    	Thread.sleep(6000);
    }
 private void clickToElement(String locator){
	    MobileElement el = waitFor(locator);
	    el.click();
	  }

private MobileElement waitFor(String locator){
	     return (MobileElement) driver.executeScript("flutter:waitFor", find.byValueKey(locator), 30);
	  }

**TestNG Results:**
FAILED: test
java.lang.NullPointerException
	at com.mgm.testscripts.mobile.flutter.FlutterTestOfficial.waitFor(FlutterTestOfficial.java:160)
	at com.mgm.testscripts.mobile.flutter.FlutterTestOfficial.clickToElement(FlutterTestOfficial.java:155)
	at com.mgm.testscripts.mobile.flutter.FlutterTestOfficial.test(FlutterTestOfficial.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)


===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================


===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================

1 of 4: Capturing dashboard statistics...
2 of 4: Capturing class metrics...
3 of 4: Capturing test metrics...
4 of 4: Capturing method metrics...

**Comment by Stephane99** [comment]
Hi,
There is a newer package 0.0.6:  
[appium-flutter-driver kotlin finder package](https://github.com/appium-userland/appium-flutter-driver/tree/main/finder/kotlin)
or. 
[kotlin finder package](https://github.com/appium-userland/finder-kotlin). 
It may work better.

Make sure you have installed the Appium server with the Flutter driver:  
appium driver install flutter. 
or update it:  
appium driver update flutter. 

Normally, when an element is not found with waitFor(), we encounter this error:
```
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Cannot execute command waitFor, server reponse {
  "isError": true,
  "response": "Timeout while executing waitFor: TimeoutException after 0:00:03.000000: Future not completed\n",
  "type": "_extensionType",
  "method": "ext.flutter.driver"
}
```

**Comment by denysord88** [comment]
I just found some useful repo https://github.com/ashwithpoojary98/javaflutterfinder/tree/master
        <dependency>
            <groupId>io.github.ashwithpoojary98</groupId>
            <artifactId>appium_flutterfinder_java</artifactId>
            <version>1.0.0</version>
        </dependency>

**Comment by ashwithpoojary98** [comment]
@obula01  https://mvnrepository.com/artifact/io.github.ashwithpoojary98/appium_flutterfinder_java
use this dependency
@denysord88 Thank you.

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-flutter-driver?tab=readme-ov-file#java-implementation
