### ISSUE TITLE
Failing to create session for no apparent reason

### ISSUE THREAD

**Issue by SanusiWasiu** [appium/appium-flutter-driver#431]
I get this every now and then, but it just seem to work after some without any change to the code.
 ERROR @wdio/runner: Error: Failed to create session.
[0-1] The session identified by fb8f89e6-a6b4-497c-ac6e-9dc39ea4d198 is not known

`[0-0] 2023-03-15T11:50:36.916Z WARN webdriver: Request failed with status 404 due to The session identified by b56f0e13-7a00-4227-bef8-322cc25a854e is not known
[0-0] 2023-03-15T11:50:36.917Z INFO webdriver: Retrying 2/3
[0-0] 2023-03-15T11:50:36.918Z INFO webdriver: [POST] http://localhost:4723/session
[0-0] 2023-03-15T11:50:36.918Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       platformName: 'Android',
[0-0]       'appium:deviceName': 'Pop',
[0-0]       'appium:platformVersion': '11.0',
[0-0]       'appium:automationName': 'Flutter',
[0-0]       'appium:app': 'app/android/app-debug.apk',
[0-0]       'appium:autoGrantPermissions': true,
[0-0]       acceptInsecureCerts: true
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     platformName: 'Android',
[0-0]     'appium:deviceName': 'Pop',
[0-0]     'appium:platformVersion': '11.0',
[0-0]     'appium:automationName': 'Flutter',
[0-0]     'appium:app': 'app/android/app-debug.apk',
[0-0]     'appium:autoGrantPermissions': true,
[0-0]     acceptInsecureCerts: true
[0-0]   }
[0-0] }
[0-0] 2023-03-15T11:50:52.266Z WARN webdriver: Request failed with status 404 due to The session identified by 3a21fb41-c8b0-4b1c-8136-4ba05c2fbffd is not known
[0-0] 2023-03-15T11:50:52.266Z INFO webdriver: Retrying 3/3
[0-0] 2023-03-15T11:50:52.267Z INFO webdriver: [POST] http://localhost:4723/session
[0-0] 2023-03-15T11:50:52.267Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       platformName: 'Android',
[0-0]       'appium:deviceName': 'Pop',
[0-0]       'appium:platformVersion': '11.0',
[0-0]       'appium:automationName': 'Flutter',
[0-0]       'appium:app': 'app/android/app-debug.apk',
[0-0]       'appium:autoGrantPermissions': true,
[0-0]       acceptInsecureCerts: true
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     platformName: 'Android',
[0-0]     'appium:deviceName': 'Pop',
[0-0]     'appium:platformVersion': '11.0',
[0-0]     'appium:automationName': 'Flutter',
[0-0]     'appium:app': 'app/android/app-debug.apk',
[0-0]     'appium:autoGrantPermissions': true,
[0-0]     acceptInsecureCerts: true
[0-0]   }
[0-0] }
[0-0] 2023-03-15T11:51:03.796Z ERROR webdriver: Request failed with status 404 due to invalid session id: The session identified by 44b9d924-96a0-4b3e-a008-7d2798f57210 is not known
[0-0] 2023-03-15T11:51:03.796Z ERROR webdriver: invalid session id: The session identified by 44b9d924-96a0-4b3e-a008-7d2798f57210 is not known
[0-0]     at getErrorFromResponseBody (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriver\build\utils.js:198:12)
[0-0]     at NodeJSRequest._request (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriver\build\request\index.js:166:60)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at startWebDriverSession (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriver\build\utils.js:68:20)
[0-0]     at Function.newSession (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriver\build\index.js:46:45)
[0-0]     at remote (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriverio\build\index.js:77:22)
[0-0]     at Runner._startSession (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\@wdio\runner\build\index.js:223:56)
[0-0]     at Runner._initSession (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\@wdio\runner\build\index.js:176:25)
[0-0]     at Runner.run (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\@wdio\runner\build\index.js:88:19)    
[0-0] 2023-03-15T11:51:03.810Z ERROR @wdio/runner: Error: Failed to create session.
[0-0] The session identified by 44b9d924-96a0-4b3e-a008-7d2798f57210 is not known
[0-0]     at startWebDriverSession (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriver\build\utils.js:73:15)
[0-0]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-0]     at Function.newSession (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriver\build\index.js:46:45)
[0-0]     at remote (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriverio\build\index.js:77:22)
[0-0]     at Runner._startSession (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\@wdio\runner\build\index.js:223:56)
[0-0]     at Runner._initSession (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\@wdio\runner\build\index.js:176:25)
[0-0]     at Runner.run (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\@wdio\runner\build\index.js:88:19)    
[0-0] FAILED in Android - C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\test\specs\android\activate.e2e.js
2023-03-15T11:51:03.959Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-03-15T11:51:03.961Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-03-15T11:51:03.964Z INFO @wdio/local-runner: Start worker 0-1 with arg:
[0-1] 2023-03-15T11:51:05.274Z INFO @wdio/local-runner: Run worker command: run
[0-1] RUNNING in Android - C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\test\specs\android\login.e2e.js
[0-1] 2023-03-15T11:51:06.234Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-1] 2023-03-15T11:51:06.346Z INFO webdriver: [POST] http://localhost:4723/session
[0-1] 2023-03-15T11:51:06.346Z INFO webdriver: DATA {
[0-1]   capabilities: {
[0-1]     alwaysMatch: {
[0-1]       platformName: 'Android',
[0-1]       'appium:deviceName': 'Pop',
[0-1]       'appium:platformVersion': '11.0',
[0-1]       'appium:automationName': 'Flutter',
[0-1]       'appium:app': 'app/android/app-debug.apk',
[0-1]       'appium:autoGrantPermissions': true,
[0-1]       acceptInsecureCerts: true
[0-1]     },
[0-1]     firstMatch: [ {} ]
[0-1]   },
[0-1]   desiredCapabilities: {
[0-1]     platformName: 'Android',
[0-1]     'appium:deviceName': 'Pop',
[0-1]     'appium:platformVersion': '11.0',
[0-1]     'appium:automationName': 'Flutter',
[0-1]     'appium:app': 'app/android/app-debug.apk',
[0-1]     'appium:autoGrantPermissions': true,
[0-1]     acceptInsecureCerts: true
[0-1]   }
[0-1] }
[0-1] 2023-03-15T11:51:18.151Z WARN webdriver: Request failed with status 404 due to The session identified by b2af9e00-8c8f-41d6-a124-0f5c93cb6034 is not known
[0-1] 2023-03-15T11:51:18.151Z INFO webdriver: Retrying 1/3
[0-1] 2023-03-15T11:51:18.151Z INFO webdriver: [POST] http://localhost:4723/session
[0-1] 2023-03-15T11:51:18.151Z INFO webdriver: DATA {
[0-1]   capabilities: {
[0-1]     alwaysMatch: {
[0-1]       platformName: 'Android',
[0-1]       'appium:deviceName': 'Pop',
[0-1]       'appium:platformVersion': '11.0',
[0-1]       'appium:automationName': 'Flutter',
[0-1]       'appium:app': 'app/android/app-debug.apk',
[0-1]       'appium:autoGrantPermissions': true,
[0-1]       acceptInsecureCerts: true
[0-1]     },
[0-1]     firstMatch: [ {} ]
[0-1]   },
[0-1]   desiredCapabilities: {
[0-1]     platformName: 'Android',
[0-1]     'appium:deviceName': 'Pop',
[0-1]     'appium:platformVersion': '11.0',
[0-1]     'appium:automationName': 'Flutter',
[0-1]     'appium:app': 'app/android/app-debug.apk',
[0-1]     'appium:autoGrantPermissions': true,
[0-1]     acceptInsecureCerts: true
[0-1]   }
[0-1] }
[0-1] 2023-03-15T11:51:28.862Z WARN webdriver: Request failed with status 404 due to The session identified by fb99cd22-c0fa-4316-b9f5-4d9ffe87cfb8 is not known
[0-1] 2023-03-15T11:51:28.862Z INFO webdriver: Retrying 2/3
[0-1] 2023-03-15T11:51:28.862Z INFO webdriver: [POST] http://localhost:4723/session
[0-1] 2023-03-15T11:51:28.862Z INFO webdriver: DATA {
[0-1]   capabilities: {
[0-1]     alwaysMatch: {
[0-1]       platformName: 'Android',
[0-1]       'appium:deviceName': 'Pop',
[0-1]       'appium:platformVersion': '11.0',
[0-1]       'appium:automationName': 'Flutter',
[0-1]       'appium:app': 'app/android/app-debug.apk',
[0-1]       'appium:autoGrantPermissions': true,
[0-1]       acceptInsecureCerts: true
[0-1]     },
[0-1]     firstMatch: [ {} ]
[0-1]   },
[0-1]   desiredCapabilities: {
[0-1]     platformName: 'Android',
[0-1]     'appium:deviceName': 'Pop',
[0-1]     'appium:platformVersion': '11.0',
[0-1]     'appium:automationName': 'Flutter',
[0-1]     'appium:app': 'app/android/app-debug.apk',
[0-1]     'appium:autoGrantPermissions': true,
[0-1]     acceptInsecureCerts: true
[0-1]   }
[0-1] }
[0-1] 2023-03-15T11:51:39.626Z WARN webdriver: Request failed with status 404 due to The session identified by 9c39ef4a-37a1-4a09-8a7b-c582a93ba1db is not known
[0-1] 2023-03-15T11:51:39.626Z INFO webdriver: Retrying 3/3
[0-1] 2023-03-15T11:51:39.626Z INFO webdriver: [POST] http://localhost:4723/session
[0-1] 2023-03-15T11:51:39.626Z INFO webdriver: DATA {
[0-1]   capabilities: {
[0-1]     alwaysMatch: {
[0-1]       platformName: 'Android',
[0-1]       'appium:deviceName': 'Pop',
[0-1]       'appium:platformVersion': '11.0',
[0-1]       'appium:automationName': 'Flutter',
[0-1]       'appium:app': 'app/android/app-debug.apk',
[0-1]       'appium:autoGrantPermissions': true,
[0-1]       acceptInsecureCerts: true
[0-1]     },
[0-1]     firstMatch: [ {} ]
[0-1]   },
[0-1]   desiredCapabilities: {
[0-1]     platformName: 'Android',
[0-1]     'appium:deviceName': 'Pop',
[0-1]     'appium:platformVersion': '11.0',
[0-1]     'appium:automationName': 'Flutter',
[0-1]     'appium:app': 'app/android/app-debug.apk',
[0-1]     'appium:autoGrantPermissions': true,
[0-1]     acceptInsecureCerts: true
[0-1]   }
[0-1] }
[0-1] 2023-03-15T11:51:50.333Z ERROR webdriver: Request failed with status 404 due to invalid session id: The session identified by fb8f89e6-a6b4-497c-ac6e-9dc39ea4d198 is not known
[0-1] 2023-03-15T11:51:50.333Z ERROR webdriver: invalid session id: The session identified by fb8f89e6-a6b4-497c-ac6e-9dc39ea4d198 is not known
[0-1]     at getErrorFromResponseBody (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriver\build\utils.js:198:12)
[0-1]     at NodeJSRequest._request (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriver\build\request\index.js:166:60)
[0-1]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-1]     at startWebDriverSession (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriver\build\utils.js:68:20)
[0-1]     at Function.newSession (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriver\build\index.js:46:45)
[0-1]     at remote (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriverio\build\index.js:77:22)
[0-1]     at Runner._startSession (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\@wdio\runner\build\index.js:223:56)
[0-1]     at Runner._initSession (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\@wdio\runner\build\index.js:176:25)
[0-1]     at Runner.run (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\@wdio\runner\build\index.js:88:19)    
[0-1] 2023-03-15T11:51:50.337Z ERROR @wdio/runner: Error: Failed to create session.
[0-1] The session identified by fb8f89e6-a6b4-497c-ac6e-9dc39ea4d198 is not known
[0-1]     at startWebDriverSession (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriver\build\utils.js:73:15)
[0-1]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-1]     at Function.newSession (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriver\build\index.js:46:45)
[0-1]     at remote (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriverio\build\index.js:77:22)
[0-1]     at Runner._startSession (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\@wdio\runner\build\index.js:223:56)
[0-1]     at Runner._initSession (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\@wdio\runner\build\index.js:176:25)
[0-1]     at Runner.run (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\@wdio\runner\build\index.js:88:19)    
[0-1] FAILED in Android - C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\test\specs\android\login.e2e.js
2023-03-15T11:51:50.488Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-03-15T11:51:50.489Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2023-03-15T11:51:50.490Z INFO @wdio/local-runner: Start worker 0-2 with arg:
[0-2] 2023-03-15T11:51:51.380Z INFO @wdio/local-runner: Run worker command: run
[0-2] RUNNING in Android - C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\test\specs\android\topup.e2e.js
[0-2] 2023-03-15T11:51:51.989Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-2] 2023-03-15T11:51:52.052Z INFO webdriver: [POST] http://localhost:4723/session
[0-2] 2023-03-15T11:51:52.053Z INFO webdriver: DATA {
[0-2]   capabilities: {
[0-2]     alwaysMatch: {
[0-2]       platformName: 'Android',
[0-2]       'appium:deviceName': 'Pop',
[0-2]       'appium:platformVersion': '11.0',
[0-2]       'appium:automationName': 'Flutter',
[0-2]       'appium:app': 'app/android/app-debug.apk',
[0-2]       'appium:autoGrantPermissions': true,
[0-2]       acceptInsecureCerts: true
[0-2]     },
[0-2]     firstMatch: [ {} ]
[0-2]   },
[0-2]   desiredCapabilities: {
[0-2]     platformName: 'Android',
[0-2]     'appium:deviceName': 'Pop',
[0-2]     'appium:platformVersion': '11.0',
[0-2]     'appium:automationName': 'Flutter',
[0-2]     'appium:app': 'app/android/app-debug.apk',
[0-2]     'appium:autoGrantPermissions': true,
[0-2]     acceptInsecureCerts: true
[0-2]   }
[0-2] }
[0-2] 2023-03-15T11:52:02.989Z WARN webdriver: Request failed with status 404 due to The session identified by 1e314967-b233-4319-91f4-bdfe582e9954 is not known
[0-2] 2023-03-15T11:52:02.989Z INFO webdriver: Retrying 1/3
[0-2] 2023-03-15T11:52:02.989Z INFO webdriver: [POST] http://localhost:4723/session
[0-2] 2023-03-15T11:52:02.989Z INFO webdriver: DATA {
[0-2]   capabilities: {
[0-2]     alwaysMatch: {
[0-2]       platformName: 'Android',
[0-2]       'appium:deviceName': 'Pop',
[0-2]       'appium:platformVersion': '11.0',
[0-2]       'appium:automationName': 'Flutter',
[0-2]       'appium:app': 'app/android/app-debug.apk',
[0-2]       'appium:autoGrantPermissions': true,
[0-2]       acceptInsecureCerts: true
[0-2]     },
[0-2]     firstMatch: [ {} ]
[0-2]   },
[0-2]   desiredCapabilities: {
[0-2]     platformName: 'Android',
[0-2]     'appium:deviceName': 'Pop',
[0-2]     'appium:platformVersion': '11.0',
[0-2]     'appium:automationName': 'Flutter',
[0-2]     'appium:app': 'app/android/app-debug.apk',
[0-2]     'appium:autoGrantPermissions': true,
[0-2]     acceptInsecureCerts: true
[0-2]   }
[0-2] }
[0-2] 2023-03-15T11:52:13.795Z WARN webdriver: Request failed with status 404 due to The session identified by bbdcff5a-7409-4cd6-bdc1-20c134ac8d47 is not known
[0-2] 2023-03-15T11:52:13.795Z INFO webdriver: Retrying 2/3
[0-2] 2023-03-15T11:52:13.795Z INFO webdriver: [POST] http://localhost:4723/session
[0-2] 2023-03-15T11:52:13.795Z INFO webdriver: DATA {
[0-2]   capabilities: {
[0-2]     alwaysMatch: {
[0-2]       platformName: 'Android',
[0-2]       'appium:deviceName': 'Pop',
[0-2]       'appium:platformVersion': '11.0',
[0-2]       'appium:automationName': 'Flutter',
[0-2]       'appium:app': 'app/android/app-debug.apk',
[0-2]       'appium:autoGrantPermissions': true,
[0-2]       acceptInsecureCerts: true
[0-2]     },
[0-2]     firstMatch: [ {} ]
[0-2]   },
[0-2]   desiredCapabilities: {
[0-2]     platformName: 'Android',
[0-2]     'appium:deviceName': 'Pop',
[0-2]     'appium:platformVersion': '11.0',
[0-2]     'appium:automationName': 'Flutter',
[0-2]     'appium:app': 'app/android/app-debug.apk',
[0-2]     'appium:autoGrantPermissions': true,
[0-2]     acceptInsecureCerts: true
[0-2]   }
[0-2] }
[0-2] 2023-03-15T11:52:24.610Z WARN webdriver: Request failed with status 404 due to The session identified by f2dd768a-fe52-49ca-929e-9ba99adc8201 is not known
[0-2] 2023-03-15T11:52:24.611Z INFO webdriver: Retrying 3/3
[0-2] 2023-03-15T11:52:24.611Z INFO webdriver: [POST] http://localhost:4723/session
[0-2] 2023-03-15T11:52:24.611Z INFO webdriver: DATA {
[0-2]   capabilities: {
[0-2]     alwaysMatch: {
[0-2]       platformName: 'Android',
[0-2]       'appium:deviceName': 'Pop',
[0-2]       'appium:platformVersion': '11.0',
[0-2]       'appium:automationName': 'Flutter',
[0-2]       'appium:app': 'app/android/app-debug.apk',
[0-2]       'appium:autoGrantPermissions': true,
[0-2]       acceptInsecureCerts: true
[0-2]     },
[0-2]     firstMatch: [ {} ]
[0-2]   },
[0-2]   desiredCapabilities: {
[0-2]     platformName: 'Android',
[0-2]     'appium:deviceName': 'Pop',
[0-2]     'appium:platformVersion': '11.0',
[0-2]     'appium:automationName': 'Flutter',
[0-2]     'appium:app': 'app/android/app-debug.apk',
[0-2]     'appium:autoGrantPermissions': true,
[0-2]     acceptInsecureCerts: true
[0-2]   }
[0-2] }
[0-2] 2023-03-15T11:52:35.776Z ERROR webdriver: Request failed with status 404 due to invalid session id: The session identified by c4a7bb96-0bfa-4708-ac3f-ec942356457d is not known
[0-2] 2023-03-15T11:52:35.776Z ERROR webdriver: invalid session id: The session identified by c4a7bb96-0bfa-4708-ac3f-ec942356457d is not known
[0-2]     at getErrorFromResponseBody (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriver\build\utils.js:198:12)
[0-2]     at NodeJSRequest._request (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriver\build\request\index.js:166:60)
[0-2]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-2]     at startWebDriverSession (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriver\build\utils.js:68:20)
[0-2]     at Function.newSession (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriver\build\index.js:46:45)
[0-2]     at remote (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriverio\build\index.js:77:22)
[0-2]     at Runner._startSession (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\@wdio\runner\build\index.js:223:56)
[0-2]     at Runner._initSession (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\@wdio\runner\build\index.js:176:25)
[0-2]     at Runner.run (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\@wdio\runner\build\index.js:88:19)    
[0-2] 2023-03-15T11:52:35.782Z ERROR @wdio/runner: Error: Failed to create session.
[0-2] The session identified by c4a7bb96-0bfa-4708-ac3f-ec942356457d is not known
[0-2]     at startWebDriverSession (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriver\build\utils.js:73:15)
[0-2]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[0-2]     at Function.newSession (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriver\build\index.js:46:45)
[0-2]     at remote (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\webdriverio\build\index.js:77:22)
[0-2]     at Runner._startSession (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\@wdio\runner\build\index.js:223:56)
[0-2]     at Runner._initSession (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\@wdio\runner\build\index.js:176:25)
[0-2]     at Runner.run (C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\node_modules\@wdio\runner\build\index.js:88:19)    
[0-2] FAILED in Android - C:\Users\wasiu.sanusi\ARMONE%20Mobile%20Automation\test\specs\android\topup.e2e.js
2023-03-15T11:52:35.904Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2023-03-15T11:52:35.905Z INFO @wdio/cli:launcher: Run onComplete hook`

**Comment by KazuCocoa** [comment]
Please share the full appium server log as GitHub GIST

**Comment by SanusiWasiu** [comment]
Hi @KazuCocoa, Do you mean i should reshare the log above just as a text and not in code format? That is all the log I got from the terminal

**Comment by KazuCocoa** [comment]
It is webdriverio's client log, not the Appium server side log.

**Comment by SanusiWasiu** [comment]
@KazuCocoa please check this out.. Not the exact error, but this has been happening continuously and I am unable to run my tests. I get this error:: 
ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: Cannot execute command waitFor, server reponse {
[0-0]   "isError": true,
[0-0]   "response": "Uncaught extension error while executing waitFor: 'package:flutter_driver/src/extension/extension.dart': Failed assertion: line 366 pos 14: 'WidgetsBinding.instance.isRootWidgetAttached || !command.requiresRootWidgetAttached': No root widget is attached; have you remembered to call runApp()?\n#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)\n#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)\n#2      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:366:14)\n#3      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:856:32)\n<asynchronous suspension>\n",
[0-0]   "type": "_extensionType",
[0-0]   "method": "ext.flutter.driver"
[0-0] }

This is the link to the appium server log github gist here: https://gist.github.com/SanusiWasiu/8b071873718386caabb1100c3025d996

**Comment by KazuCocoa** [comment]
The error itself came from the DartVM/Flutter internal. Nothing can do as this driver I guess, unfortunately.
