### ISSUE TITLE
After switching from NATIVE_APP to FLUTTER context. Unable to find the flutter element and the error is, "Encountered internal error running command: Error: {}"

### ISSUE THREAD

**Issue by pothurajtharun** [appium/appium-flutter-driver#474]
Appium v2.0.0-beta.71
Flutter Driver Version : @1.14.4
autoamtionName=Flutter

**Steps to reproduce :** 

1. Switch to NATIVE_APP context.
2. Perform any operation on native elements.
3. Switch to FLUTTER context.
4. WaitFor an flutter element.

Unable to find an fluter element eventhough its on the screen. 

**Code :** 
```
((SupportsContextSwitching) driver).context("NATIVE_APP");
driver.findElement(By.id("android:id/switch_widget")).click();
driver.findElement(By.xpath("//android.widget.ImageButton[@content-desc='Navigate up']")).click();
((SupportsContextSwitching) driver).context("FLUTTER");
driver.executeScript("flutter:waitFor", finder.byText("Your Sources"), 30);
```

```
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: {}
Build info: version: '4.9.0', revision: 'd7057100a6'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.6.5', java.version: '11.0.19'
Driver info: io.appium.java_client.android.AndroidDriver
Command: [f2c63f94-20dd-4d79-a066-be9733b3b52c, executeScript {script=flutter:waitFor, args=[{element-6066-11e4-a52e-4f735466cecf=eyJ0ZXh0IjoiWW91ciBTb3VyY2VzIiwiZmluZGVyVHlwZSI6IkJ5VGV4dCJ9}, 30]}]
Capabilities {appium:address: 0.0.0.0, appium:allowCors: false, appium:allowInsecure: [], appium:app: /usr/local/automation/Mobil..., appium:appActivity: com.example.flutter_rust_br..., appium:appPackage: com.example.flutter_rust_br..., appium:automationName: Flutter, appium:basePath: , appium:callbackPort: 4723, appium:clearDeviceLogsOnStart: true, appium:clearSystemFiles: true, appium:debugLogSpacing: false, appium:denyInsecure: [], appium:deviceName: Google Pixel 7 Pro, appium:driver: {xcuitest: {wdaLocalPort: 8100}}, appium:extraArgs: [], appium:fastReset: true, appium:keepAliveTimeout: 600, appium:localTimezone: false, appium:logFile: /Users/tharunpothuraj/Docum..., appium:logNoColors: false, appium:logTimestamp: false, appium:loglevel: debug, appium:longStacktrace: false, appium:newCommandTimeout: 1000, appium:noPermsCheck: false, appium:platformVersion: 13, appium:port: 4766, appium:printPageSourceOnFindFailure: true, appium:relaxedSecurityEnabled: true, appium:sessionOverride: false, appium:skipUninstall: true, appium:strictCaps: false, appium:subcommand: server, appium:tmpDir: /var/folders/9p/02fsf43s28l..., appium:udid: 2B141FDH3001WV, appium:useDrivers: [], appium:useJSONSource: true, appium:usePlugins: [], appium:waitForQuiescence: false, platformName: ANDROID}
Session ID: f2c63f94-20dd-4d79-a066-be9733b3b52c
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:193)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:480)
	at com.wdc.qa.clients.corbita.tests.mobile.homepage.HomeTest.verifyYourSources(HomeTest.java:66)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:829)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1251)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1251)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at org.testng.TestNG.runSuites(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1067)
	at com.wdc.qa.core.runner.AutomatedTestingRunner.runSuites(AutomatedTestingRunner.java:152)
	at com.wdc.qa.core.runner.AutomatedTestingRunner.main(AutomatedTestingRunner.java:85)
```

**Apppium Server Log:** 
[appium-port-4766.log](https://github.com/appium-userland/appium-flutter-driver/files/11585439/appium-port-4766.log)

**Comment by KazuCocoa** [comment]
After the native context's click action,  the Flutter session was closed. It might indicate the Dart VM (the test app's flutter layer itself) closed the session..?

```
2023-05-28 18:41:58:518 [HTTP] --> POST /session/f2c63f94-20dd-4d79-a066-be9733b3b52c/element/00000000-0000-0044-ffff-ffff00000130/click
2023-05-28 18:41:58:518 [HTTP] {"id":"00000000-0000-0044-ffff-ffff00000130"}
2023-05-28 18:41:58:519 [FlutterDriver@6624 (f2c63f94)] Calling AppiumDriver.click() with args: ["00000000-0000-0044-ffff-ffff00000130","f2c63f94-20dd-4d79-a066-be9733b3b52c"]
2023-05-28 18:41:58:519 [FlutterDriver] Executing proxied driver command 'click'
2023-05-28 18:41:58:519 [AndroidUiautomator2Driver@d13d (9b15e2f6)] Matched '/element/00000000-0000-0044-ffff-ffff00000130/click' to command name 'click'
2023-05-28 18:41:58:520 [AndroidUiautomator2Driver@d13d (9b15e2f6)] Proxying [POST /element/00000000-0000-0044-ffff-ffff00000130/click] to [POST http://127.0.0.1:8200/session/55c6a69e-c7d1-4b84-a256-f1a28e629c53/element/00000000-0000-0044-ffff-ffff00000130/click] with body: {"element":"00000000-0000-0044-ffff-ffff00000130"}
2023-05-28 18:41:58:570 [AndroidUiautomator2Driver@d13d (9b15e2f6)] Got response with status 200: {"sessionId":"55c6a69e-c7d1-4b84-a256-f1a28e629c53","value":null}
2023-05-28 18:41:58:571 [FlutterDriver@6624 (f2c63f94)] Responding to client with driver.click() result: null
2023-05-28 18:41:58:572 [HTTP] <-- POST /session/f2c63f94-20dd-4d79-a066-be9733b3b52c/element/00000000-0000-0044-ffff-ffff00000130/click 200 53 ms - 14
2023-05-28 18:41:58:572 [HTTP] 
2023-05-28 18:41:58:664 [FlutterDriver] Connection to ws://127.0.0.1:42531/oL_o7Ij7-2k=/ws closed
2023-05-28 18:41:58:665 [FlutterDriver] Connection to ws://127.0.0.1:42531/oL_o7Ij7-2k=/ws closed
2023-05-28 18:42:04:552 [HTTP] --> POST /session/f2c63f94-20dd-4d79-a066-be9733b3b52c/context
2023-05-28 18:42:04:552 [HTTP] {"name":"FLUTTER"}
```

Did the click close flutter something? (e.g. the app is hybrid app, and the click action closes the flutter's activity)

**Comment by pothurajtharun** [comment]
Thanks @KazuCocoa for the pointing the isssue. I will discuss with my dev team and come back with the response.
