### ISSUE TITLE
Rotate iOS Simulator to Landscape is not working

### ISSUE THREAD

**Issue by denysord88** [appium/appium-flutter-driver#496]
I want to test my Flutter app in a portrait and landscape mode, but driver.rotate is not working. Looks like it's not implemented yet.

Is there any way to rotate device with appium-flutter-driver ?

My Java code:

```
        if (platform.equals(MobilePlatform.IOS)) {
            ((IOSDriver) driver).context("NATIVE_APP");
            System.out.println("   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! trying to totate");
            ((IOSDriver) driver).rotate(new DeviceRotation(0, 0, 90));
            ((JavascriptExecutor) driver).executeScript("mobile:setAppearance", ImmutableMap.of("style", DEVICE_THEME.toLowerCase()));
            ((IOSDriver) driver).context("FLUTTER");
        }
```

Appium logs:
```
[HTTP] --> POST /wd/hub/session/ac2ec12c-dc27-4760-9b34-617c88b1663e/context
[HTTP] {"name":"NATIVE_APP"}
[debug] [FlutterDriver@a5d7 (ac2ec12c)] Calling AppiumDriver.setContext() with args: ["NATIVE_APP","ac2ec12c-dc27-4760-9b34-617c88b1663e"]
[debug] [FlutterDriver] Executing Flutter driver command 'setContext'
[debug] [XCUITestDriver@04ba (5f2787c2)] Attempting to set context to 'NATIVE_APP' from 'NATIVE_APP'
[debug] [XCUITestDriver@04ba (5f2787c2)] Already in 'NATIVE_APP' context. Doing nothing.
[debug] [FlutterDriver@a5d7 (ac2ec12c)] Responding to client with driver.setContext() result: null
[HTTP] <-- POST /wd/hub/session/ac2ec12c-dc27-4760-9b34-617c88b1663e/context 200 3 ms - 14
[HTTP] 
   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! trying to totate
[HTTP] --> POST /wd/hub/session/ac2ec12c-dc27-4760-9b34-617c88b1663e/rotation
[HTTP] {"x":0,"y":0,"z":90}
[debug] [FlutterDriver@a5d7 (ac2ec12c)] Calling AppiumDriver.setRotation() with args: [0,0,90,"ac2ec12c-dc27-4760-9b34-617c88b1663e"]
[debug] [FlutterDriver] Executing proxied driver command 'setRotation'
[debug] [XCUITestDriver@04ba (5f2787c2)] Executing command 'setRotation'
[debug] [FlutterDriver@a5d7 (ac2ec12c)] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
[debug] [FlutterDriver@a5d7 (ac2ec12c)]     at XCUITestDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:100:13)
[debug] [FlutterDriver@a5d7 (ac2ec12c)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [FlutterDriver@a5d7 (ac2ec12c)]     at XCUITestDriver.executeCommand (/Users/denysord88/.appium/node_modules/appium-flutter-driver/node_modules/appium-xcuitest-driver/lib/driver.js:785:12)
[debug] [FlutterDriver@a5d7 (ac2ec12c)]     at FlutterDriver.executeCommand (/Users/denysord88/.appium/node_modules/appium-flutter-driver/lib/driver.ts:162:24)
[debug] [FlutterDriver@a5d7 (ac2ec12c)]     at defaultBehavior (/usr/local/lib/node_modules/appium/lib/appium.js:684:14)
[debug] [FlutterDriver@a5d7 (ac2ec12c)]     at AppiumDriver.executeWrappedCommand (/usr/local/lib/node_modules/appium/lib/appium.js:774:16)
[debug] [FlutterDriver@a5d7 (ac2ec12c)]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:696:17)
[debug] [FlutterDriver@a5d7 (ac2ec12c)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:387:19)
[HTTP] <-- POST /wd/hub/session/ac2ec12c-dc27-4760-9b34-617c88b1663e/rotation 405 16 ms - 1053
[HTTP] 
```

**Comment by denysord88** [comment]
Same for Android
```
        } else {
            ((AndroidDriver) driver).context("NATIVE_APP");
            System.out.println("   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! trying to totate");
            ((AndroidDriver) driver).rotate(new DeviceRotation(0, 0, 90));
            ((JavascriptExecutor) driver).executeScript("mobile:setAppearance", ImmutableMap.of("style", DEVICE_THEME.toLowerCase()));
            ((AndroidDriver) driver).context("FLUTTER");
        }
```
Logs
```
   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! trying to totate
[HTTP] --> POST /wd/hub/session/7e708a61-be1c-44a6-8ebc-4992f81be51f/rotation
[HTTP] {"x":0,"y":0,"z":90}
[debug] [FlutterDriver@516f (7e708a61)] Calling AppiumDriver.setRotation() with args: [0,0,90,"7e708a61-be1c-44a6-8ebc-4992f81be51f"]
[debug] [FlutterDriver] Executing proxied driver command 'setRotation'
[debug] [FlutterDriver@516f (7e708a61)] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
[debug] [FlutterDriver@516f (7e708a61)]     at AndroidUiautomator2Driver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:100:13)
[debug] [FlutterDriver@516f (7e708a61)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [FlutterDriver@516f (7e708a61)]     at FlutterDriver.executeCommand (/Users/denysord88/.appium/node_modules/appium-flutter-driver/lib/driver.ts:162:24)
[debug] [FlutterDriver@516f (7e708a61)]     at defaultBehavior (/usr/local/lib/node_modules/appium/lib/appium.js:684:14)
[debug] [FlutterDriver@516f (7e708a61)]     at AppiumDriver.executeWrappedCommand (/usr/local/lib/node_modules/appium/lib/appium.js:774:16)
[debug] [FlutterDriver@516f (7e708a61)]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:696:17)
[debug] [FlutterDriver@516f (7e708a61)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:387:19)
[HTTP] <-- POST /wd/hub/session/7e708a61-be1c-44a6-8ebc-4992f81be51f/rotation 405 20 ms - 906
[HTTP] 
```

**Comment by KazuCocoa** [comment]
It looks like they also need to do similar thing in https://github.com/appium-userland/appium-flutter-driver/blob/main/driver/lib/driver.ts#L116-L119

**Comment by KazuCocoa** [comment]
Could you try out `1.17.0`?
Then, could you try device orientation? `setOrientation` and `getOrientation` for Java

**Comment by denysord88** [comment]
I used 1.14.3 before and after I switched to 1.17.0 the framework started to boot a new iOS Simulator instance every time I'm starting the tests.
The XCode is trying to build WDA and fails sometimes.. Dart Observatory URL is not always present.. something crazy happening with my tests.

I tried to downgrade version back to 1.14.3 and it started working fine (but without rotation). But after I switched back to 1.17.0 it's starting fails in a random places again.

I'm executing the following commands to change the version on my MacOS terminal:
```
sudo rm -rf /Users/denysord88/.appium/node_modules/appium-flutter-driver
sudo appium driver uninstall flutter
sudo appium driver install --source=npm appium-flutter-driver@1.17.0
```
Did I miss something? How to clean the WDA xcode project? And why on 1.17.0 I can't use prebuild wda anymore?

**Comment by denysord88** [comment]
For `((IOSDriver) driver).rotate(ScreenOrientation.LANDSCAPE);`
the same:
```
   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! trying to totate
[HTTP] --> POST /wd/hub/session/5e10e75f-b321-4a9b-989e-09a2b2680f31/orientation
[HTTP] {"orientation":"LANDSCAPE"}
[debug] [FlutterDriver@95c8 (5e10e75f)] Calling AppiumDriver.setOrientation() with args: ["LANDSCAPE","5e10e75f-b321-4a9b-989e-09a2b2680f31"]
[debug] [FlutterDriver] Executing proxied driver command 'setOrientation'
[debug] [XCUITestDriver@aed3 (7be2bb2a)] Executing command 'setOrientation'
[debug] [FlutterDriver@95c8 (5e10e75f)] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
[debug] [FlutterDriver@95c8 (5e10e75f)]     at XCUITestDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:101:13)
[debug] [FlutterDriver@95c8 (5e10e75f)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [FlutterDriver@95c8 (5e10e75f)]     at XCUITestDriver.executeCommand (/Users/denysord88/.appium/node_modules/appium-flutter-driver/node_modules/appium-xcuitest-driver/lib/driver.js:1082:12)
[debug] [FlutterDriver@95c8 (5e10e75f)]     at FlutterDriver.executeCommand (/Users/denysord88/.appium/node_modules/appium-flutter-driver/lib/driver.ts:170:24)
[debug] [FlutterDriver@95c8 (5e10e75f)]     at defaultBehavior (/usr/local/lib/node_modules/appium/lib/appium.js:684:14)
[debug] [FlutterDriver@95c8 (5e10e75f)]     at AppiumDriver.executeWrappedCommand (/usr/local/lib/node_modules/appium/lib/appium.js:774:16)
[debug] [FlutterDriver@95c8 (5e10e75f)]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:696:17)
[debug] [FlutterDriver@95c8 (5e10e75f)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:393:19)
[HTTP] <-- POST /wd/hub/session/5e10e75f-b321-4a9b-989e-09a2b2680f31/orientation 405 34 ms - 1054
[HTTP] 
```

**Comment by KazuCocoa** [comment]
Could you share the full appium log? (as GIST?)
I'll take a look tonight if i have time

---

> I tried to downgrade version back to 1.14.3 and it started working fine (but without rotation). But after I switched back to 1.17.0 it's starting fails in a random places again.

If this has been uia2/xcuitest driver related, their version update might affect in `1.16.0` around `1.15.0` https://github.com/appium-userland/appium-flutter-driver/blob/main/driver/CHANGELOG.md#1160

**Comment by KazuCocoa** [comment]
Need to check the full log further to fig into more.

**Comment by samitrepo** [comment]
None of the below Script is working for IOS in Flutter when simple Appium Driver is used.

**1. ((IOSDriver) driver).rotate(new DeviceRotation(0, 0, 90));
2. ((IOSDriver) driver).rotate(ScreenOrientation.LANDSCAPE);**



Where as below working superb for Android in Flutter when simple Appium Driver is used.

_1. ((AndroidDriver) driver).rotate(ScreenOrientation.LANDSCAPE);_

Please advice !! @KazuCocoa
