### ISSUE TITLE
Unable to test app `after terminate_app` and `activate_app`

### ISSUE THREAD

**Issue by oligazar** [appium/appium-flutter-driver#553]
I'm trying to test launching app with deep link after it's being terminated. But after executing `driver.terminate_app` and `driver.get` flutter driver is unable to find or interact with any widgets on the screen. 

driver.terminate_app('app_id') results in closing dart vm connection
```
[debug] [FlutterDriver] Executing proxied driver command 'execute'
[AndroidUiautomator2Driver@0e7e (d5ac6982)] Executing native command 'mobile: terminateApp'
[AndroidUiautomator2Driver@0e7e (d5ac6982)] Terminating 'com.app.devo'
[debug] [ADB] Getting IDs of all 'com.app.devo' processes
[debug] [ADB] Running '/Users/admin/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pgrep -f \(\[\[:blank:\]\]\|\^\)com\.apphq\.devo\(\[\[:blank:\]\]\|\$\)'
[debug] [ADB] Running '/Users/admin/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop com.apphq.devo'
[FlutterDriver] Connection to ws://127.0.0.1:38399/DWHjjOnA_jk=/ws closed
```
calling `driver.get("https://deep.link.com")` opens the app, but doesn't establish a new connection.
So I tried calling `driver.activate_app('com.apphq.devo')`, as stated in [documentation](https://github.com/appium/appium-flutter-driver), 

> Activate the app via driver.activate_app or mobile:activateApp command
> Then, appium-flutter-driver establish a connection with the Dart VM

But the connection is never established.

I also tried calling `driver.execute_script("flutter:connectObservatoryWsUrl")`. That returned `NotImplementedError: Method is not implemented` error
```
Calling AppiumDriver.execute() with args: ["flutter:connectObservatoryWsUrl",[],"277be7e6-c837-432e-8cce-1e36d2d889de"]
[debug] [FlutterDriver] Executing proxied driver command 'execute'
[debug] [FlutterDriver@4ef4 (277be7e6)] Encountered internal error running command: NotImplementedError: Method is not implemented
```

If `driver.execute_script("flutter:connectObservatoryWsUrl")` is called from a flutter context, the error would be `Command not support`:
```
{'status': 500, 'value': '{"value":{"error":"unknown error","message":"An unknown server-side error occurred while processing the command. Original error: Command not support: \\"flutter:connectObservatoryWsUrl\\"","stacktrace":"UnknownError: An unknown server-side error occurred while processing the command. Original error: Command not support: \\"flutter:connectObservatoryWsUrl\\"\\n    at getResponseForW3CError (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1073:9)\\n    at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:491:57)"}}'}
```

So I need a reliable way to re-establish dart vm connection after the app was terminated during a test session. 

Here's the code example
```
    driver.switch_to.context('NATIVE_APP')

    driver.terminate_app('com.apphq.devo')

    driver.activate_app('com.apphq.devo')

    driver.execute_script("flutter:connectObservatoryWsUrl")

    driver.get("https://devo.app.com")

    driver.switch_to.context('FLUTTER')

    sign_in_btn_finder = finder.by_text('Sign in')
    sign_in_btn = FlutterElement(driver, sign_in_btn_finder)
    print("Clicking 'Sign in' button")
    sign_in_btn.click()
```

And this is the log output:
```
[debug] [FlutterDriver] Executing proxied driver command 'execute'
[AndroidUiautomator2Driver@0e7e (d5ac6982)] Executing native command 'mobile: terminateApp'
[AndroidUiautomator2Driver@0e7e (d5ac6982)] Terminating 'com.apphq.devo'
[debug] [ADB] Getting IDs of all 'com.apphq.devo' processes
[debug] [ADB] Running '/Users/admin/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pgrep -f \(\[\[:blank:\]\]\|\^\)com\.apphq\.devo\(\[\[:blank:\]\]\|\$\)'
[debug] [ADB] Running '/Users/admin/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am force-stop com.apphq.devo'
[FlutterDriver] Connection to ws://127.0.0.1:38399/DWHjjOnA_jk=/ws closed
[AndroidUiautomator2Driver@0e7e (d5ac6982)] Querying the state of 'com.apphq.devo'
[debug] [ADB] Getting install status for com.apphq.devo
[debug] [ADB] Running '/Users/admin/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pm path com.apphq.devo'
[debug] [ADB] 'com.apphq.devo' is installed
[debug] [ADB] Getting IDs of all 'com.apphq.devo' processes
[debug] [ADB] Running '/Users/admin/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell pgrep -f \(\[\[:blank:\]\]\|\^\)com\.apphq\.devo\(\[\[:blank:\]\]\|\$\)'
[AndroidUiautomator2Driver@0e7e (d5ac6982)] 'com.apphq.devo' has been successfully terminated
[debug] [FlutterDriver@4ef4 (277be7e6)] Responding to client with driver.execute() result: true
[HTTP] <-- POST /session/277be7e6-c837-432e-8cce-1e36d2d889de/execute/sync 200 760 ms - 14
[HTTP] 
[HTTP] --> POST /session/277be7e6-c837-432e-8cce-1e36d2d889de/execute/sync
[HTTP] {"script":"mobile: activateApp","args":[{"appId":"com.apphq.devo","bundleId":"com.apphq.devo"}]}
[debug] [FlutterDriver@4ef4 (277be7e6)] Calling AppiumDriver.execute() with args: ["mobile: activateApp",[{"appId":"com.apphq.devo","bundleId":"com.apphq.devo"}],"277be7e6-c837-432e-8cce-1e36d2d889de"]
[debug] [FlutterDriver] Executing proxied driver command 'execute'
[AndroidUiautomator2Driver@0e7e (d5ac6982)] Executing native command 'mobile: activateApp'
[debug] [AndroidUiautomator2Driver@0e7e (d5ac6982)] Activating 'com.apphq.devo'
[debug] [ADB] Running '/Users/admin/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell cmd package resolve-activity --brief com.apphq.devo'
[debug] [ADB] Running '/Users/admin/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 shell am start-activity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000 -n com.apphq.devo/com.apphq.MainActivity'
[debug] [AndroidUiautomator2Driver@0e7e (d5ac6982)] Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.appohq.devo/com.apphq.MainActivity }
[debug] [FlutterDriver@4ef4 (277be7e6)] Responding to client with driver.execute() result: null
[HTTP] <-- POST /session/277be7e6-c837-432e-8cce-1e36d2d889de/execute/sync 200 315 ms - 14
[HTTP] 
[HTTP] --> POST /session/277be7e6-c837-432e-8cce-1e36d2d889de/execute/sync
[HTTP] {"script":"flutter:connectObservatoryWsUrl","args":[]}
[debug] [FlutterDriver@4ef4 (277be7e6)] Calling AppiumDriver.execute() with args: ["flutter:connectObservatoryWsUrl",[],"277be7e6-c837-432e-8cce-1e36d2d889de"]
[debug] [FlutterDriver] Executing proxied driver command 'execute'
[debug] [FlutterDriver@4ef4 (277be7e6)] Encountered internal error running command: NotImplementedError: Method is not implemented
[debug] [FlutterDriver@4ef4 (277be7e6)]     at AndroidUiautomator2Driver.execute (/Users/admin/.appium/node_modules/appium-flutter-driver/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/execute.js:13:11)
[debug] [FlutterDriver@4ef4 (277be7e6)]     at commandExecutor (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:107:18)
[debug] [FlutterDriver@4ef4 (277be7e6)]     at /opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:171:12
[debug] [FlutterDriver@4ef4 (277be7e6)]     at AsyncLock._promiseTry (/opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:304:31)
[debug] [FlutterDriver@4ef4 (277be7e6)]     at exec (/opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:170:9)
[debug] [FlutterDriver@4ef4 (277be7e6)]     at AsyncLock.acquire (/opt/homebrew/lib/node_modules/appium/node_modules/async-lock/lib/index.js:187:3)
[debug] [FlutterDriver@4ef4 (277be7e6)]     at AndroidUiautomator2Driver.executeCommand (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:123:39)
[debug] [FlutterDriver@4ef4 (277be7e6)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [FlutterDriver@4ef4 (277be7e6)]     at FlutterDriver.executeCommand (/Users/admin/.appium/node_modules/appium-flutter-driver/lib/driver.ts:170:24)
[debug] [FlutterDriver@4ef4 (277be7e6)]     at defaultBehavior (/opt/homebrew/lib/node_modules/appium/lib/appium.js:684:14)
[debug] [FlutterDriver@4ef4 (277be7e6)]     at AppiumDriver.executeWrappedCommand (/opt/homebrew/lib/node_modules/appium/lib/appium.js:774:16)
[debug] [FlutterDriver@4ef4 (277be7e6)]     at AppiumDriver.executeCommand (/opt/homebrew/lib/node_modules/appium/lib/appium.js:696:17)
[debug] [FlutterDriver@4ef4 (277be7e6)]     at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:393:19)
[HTTP] <-- POST /session/277be7e6-c837-432e-8cce-1e36d2d889de/execute/sync 405 73 ms - 1660

```

**Comment by KazuCocoa** [comment]
Please attach the full appium log.


> I also tried calling driver.execute_script("flutter:connectObservatoryWsUrl"). That returned NotImplementedError: Method is not implemented error

Potentially indicates the driver was old or tried in no FLUTTER context

**Comment by KazuCocoa** [comment]
> But the connection is never established.

As another possible reason, the deep link method did not print the observatory url in the system log. Then appium flutter driver has no way to attach to the DartVM

**Comment by oligazar** [comment]
> Potentially indicates the driver was old or tried in no FLUTTER context

What does it mean "driver was old"?
I also tried running it in FLUTTER context, I mentioned it in the question. It returned an error: 
`An unknown server-side error occurred while processing the command. Original error: Command not support: "flutter:connectObservatoryWsUrl`

**Comment by oligazar** [comment]
> As another possible reason, the deep link method did not print the observatory url in the system log. Then appium flutter driver has no way to attach to the DartVM

Where exactly the observatory url should be printed? In appium's logs?

In [docs](https://github.com/appium/appium-flutter-driver) it's mentioned that `driver.activate_app` should establish a connection with the Dart VM, but I don't see it happening. I also don't see it printing the observatory url or any attempt to connect to it.

I tried to ignore deep link part and only did this set of calls:
```
    driver.switch_to.context('NATIVE_APP')
    driver.terminate_app('com.apphq.devo')
    driver.activate_app('com.apphq.devo')
    driver.switch_to.context('FLUTTER')
    driver.execute_script("flutter:connectObservatoryWsUrl")
```
The result is the same. Please see logs:
[AppiumLog.txt](https://github.com/appium/appium-flutter-driver/files/12495070/AppiumLog.txt)

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-flutter-driver/blob/main/driver/CHANGELOG.md
The connectObservatoryWsUrl command was added in v1.18.0 while you were using appium flutter driver v1.17.0.

**Comment by KazuCocoa** [comment]
> Where exactly the observatory url should be printed?

It is in the logcat

**Comment by oligazar** [comment]
@KazuCocoa Thank you for quick reply! Updated the driver. Now `activateApp` tries establishing a connection to the Dart Observatory, but result is `Error: Cannot connect to the Dart Observatory URL`. Please see logs attached

[AppiumLog.txt](https://github.com/appium/appium-flutter-driver/files/12499028/AppiumLog.txt)

Maybe some capabilities are required for this to work?

**Comment by oligazar** [comment]
Although, activate_app results in error, this code now works as expected
```
    driver.switch_to.context('NATIVE_APP')
    driver.terminate_app('com.apphq.devo')
    driver.get("https://devo.app.com")
    driver.switch_to.context('FLUTTER')
    driver.execute_script("flutter:connectObservatoryWsUrl")
```

**Comment by KazuCocoa** [comment]
Then, it could be timing stuff that printed latest valid observatory url. Both are valid way to start an app

https://github.com/appium/appium-flutter-driver?tab=readme-ov-file#several-ways-to-start-an-application

**Comment by oligazar** [comment]
Hey, @KazuCocoa!  I have another but related issue to this one. 

As a step in my flutter app iOS test I need to install a native iOS app. I used `driver.activate_app('com.app.bundle_id')` line in the native context to open the app and it worked just fine. But after the update, the line returns 
```
No observatory URL matching to '...' was found in the device log. Please make sure the application under test is configured properly according to https://github.com/appium-userland/appium-flutter-driver#usage and that it does not crash on startup.
```

I also tried `driver.executeScript("mobile: launchApp", {"bundleId": "com.app.bundle_id"})` with no success.

Any suggestions on how to open and interact with a native iOS app in the middle of a flutter app testing session?

**Comment by KazuCocoa** [comment]
Then, it needs to have an option to not listen the observatory url

**Comment by oligazar** [comment]
> Then, it needs to have an option to not listen the observatory url

`driver.activate_app('com.app.bundle_id')` doesn't seem to have such an option. 

Can you please give me an example how it might look like?

**Comment by KazuCocoa** [comment]
It will be a new option, so not in current options.
I'll create a PR later

**Comment by KazuCocoa** [comment]
please try out https://github.com/appium/appium-flutter-driver/blob/main/driver/CHANGELOG.md#1220
