### ISSUE TITLE
Uncaught extension error while executing get_text

### ISSUE THREAD

**Issue by baselalali** [appium/appium-flutter-driver#585]
Background:

I am working on a Flutter application and using Flutter Driver for automated testing. In my test script, I'm attempting to retrieve the text of an element with the value key "imprint_link."

Expected Behavior:

I expect to be able to retrieve the text of the element with the value key "imprint_link" using the getText() method.

Current Behavior:

When I try to get the text of the element using fnd.byValueKey("imprint_link").getText(), I encounter the following error:

![image](https://github.com/appium/appium-flutter-driver/assets/82577381/97874a27-f1cb-4e83-aa19-f2613472c01d)

```
{
  "isError": true,
  "response": "Uncaught extension error while executing get_text: Unsupported operation: Type Text is currently not supported by getText\n#0 CommandHandlerFactory._getText (package:flutter_driver/src/common/handler_factory.dart:422:7)\n<asynchronous suspension>\n#1 FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:376:31)\n<asynchronous suspension>\n#2 BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:936:18)\n<asynchronous suspension>\n",
  "type": "_extensionType",
  "method": "ext.flutter.driver"
}




`[Appium]   - xcuitest@4.35.0 (automationName 'XCUITest')
[Appium]   - uiautomator2@2.29.8 (automationName 'UiAutomator2')
[Appium]   - flutter@1.23.0 (automationName 'Flutter')`

```

**Comment by KazuCocoa** [comment]
Duplicate of https://github.com/appium/appium-flutter-driver/issues/297 ?

**Comment by KazuCocoa** [comment]
i wondered if the parent element supported the getText() as Flutter's implementation, so `descendant` finder helps for it

**Comment by baselalali** [comment]
we noticed the lib of some issues by finding element: ashwithpoojary98

https://github.com/ashwithpoojary98/javaflutterfinder/issues/8#issuecomment-1541861979

We uses the lib of https://github.com/5v1988/appium-flutter-client
