### ISSUE TITLE
Using find.descendant in find.descendant results in a DartVM error

### ISSUE THREAD

**Issue by williampearl** [appium/appium-flutter-driver#586]
Hello, I am trying to use find.descendant in a find.descendant like so
```typescript
const id = descendant({
    of: find.byValueKey(`history_work_order_item_1`),
    matching: find.descendant({
      of: find.byType("WorkOrderStatusIndicator"),
      matching: find.byType("Text"),
      matchRoot: false,
      firstMatchOnly: true,
    }),
    matchRoot: false,
    firstMatchOnly: true,
  }); 
const status = await driver.getElementText(id);  
console.log(status);
```
This is the output in the Appium server log
```
[debug] [FlutterDriver@89ba (e366c792)] Calling AppiumDriver.getText() with args: ["eyJmaW5kZXJUeXBlIjoiRGVzY2VuZGFudCIsImZpcnN0TWF0Y2hPbmx5Ijp0cnVlLCJtYXRjaFJvb3QiOmZhbHNlLCJvZiI6IntcImZpbmRlclR5cGVcIjpcIkJ5VmFsdWVLZXlcIixcImtleVZhbHVlU3RyaW5nXCI6XCJoaXN0b3J5X3dvcmtfb3JkZXJfaXRlbV8xXCIsXCJrZXlWYWx1ZVR5cGVcIjpcIlN0cmluZ1wifSIsIm1hdGNoaW5nIjoie1wiZmluZGVyVHlwZVwiOlwiRGVzY2VuZGFudFwiLFwiZmlyc3RNYXRjaE9ubHlcIjp0cnVlLFwibWF0Y2hSb290XCI6ZmFsc2UsXCJvZlwiOlwie1xcXCJmaW5kZXJUeXBlXFxcIjpcXFwiQnlUeXBlXFxcIixcXFwidHlwZVxcXCI6XFxcIldvcmtPcmRlclN0YXR1c0luZGljYXRvclxcXCJ9XCIsXCJtYXRjaGluZ1wiOlwie1xcXCJmaW5kZXJUeXBlXFxcIjpcXFwiQnlUeXBlXFxcIixcXFwidHlwZVxcXCI6XFxcIlRleHRcXFwifVwifSJ9","e366c792-142b-4c8c-8a04-75a1200a2efa"]
[debug] [FlutterDriver] Executing Flutter driver command 'getText'
[debug] [FlutterDriver] >>> {"command":"get_text","finderType":"Descendant","firstMatchOnly":true,"matchRoot":false,"of":"{\"finderType\":\"ByValueKey\",\"keyValueString\":\"history_work_order_item_1\",\"keyValueType\":\"String\"}","matching":"{\"finderType\":\"Descendant\",\"firstMatchOnly\":true,\"matchRoot\":false,\"of\":\"{\\\"finderType\\\":\\\"ByType\\\",\\\"type\\\":\\\"WorkOrderStatusIndicator\\\"}\",\"matching\":\"{\\\"finderType\\\":\\\"ByType\\\",\\\"type\\\":\\\"Text\\\"}\"}"}
[debug] [FlutterDriver] <<< {"isError":true,"response":"Uncaught extension error while executing get_text: type 'bool' is not a subtype of type 'String' in type cast\n#0      new LinkedHashMap.from.<anonymous closure> (dart:collection/linked_hash_map.dart:187:26)\n#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)\n#2      new LinkedHashMap.from (dart:collection/linked_hash_map.dart:186:11)\n#3      Descendant.deserialize (package:flutter_driver/src/common/find.dart:329:9)\n#4      DeserializeFinderFactory.deserializeFinder (package:flutter_driver/src/common/deserialization_factory.dart:32:44)\n#5      FlutterDriverExtension.deserializeFinder (package:flutter_driver/src/extension/extension.dart:401:18)\n#6      new CommandWithTarget.deserialize (package:flutter_driver/src/common/find.dart:32:30)\n#7      new GetText.deserialize (package:flutter_driver/src/common/text.dart:14:64)\n#8      DeserializeCommandFactory.deserializeCommand (package:flutter_driver/src/common/deserialization_factory.dart:49:39)\n#9      FlutterDriverExtension.deserializeCommand (package:flutter_driver/src/extension/extension.dart:421:18)\n#10     FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:365:31)\n#11     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:855:32)\n<asynchronous suspension>\n","type":"_extensionType","method":"ext.flutter.driver"} | previous command get_text
[debug] [FlutterDriver@89ba (e366c792)] Encountered internal error running command: Error: Cannot execute command get_text, server reponse {
[debug] [FlutterDriver@89ba (e366c792)]   "isError": true,
[debug] [FlutterDriver@89ba (e366c792)]   "response": "Uncaught extension error while executing get_text: type 'bool' is not a subtype of type 'String' in type cast\n#0      new LinkedHashMap.from.<anonymous closure> (dart:collection/linked_hash_map.dart:187:26)\n#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)\n#2      new LinkedHashMap.from (dart:collection/linked_hash_map.dart:186:11)\n#3      Descendant.deserialize (package:flutter_driver/src/common/find.dart:329:9)\n#4      DeserializeFinderFactory.deserializeFinder (package:flutter_driver/src/common/deserialization_factory.dart:32:44)\n#5      FlutterDriverExtension.deserializeFinder (package:flutter_driver/src/extension/extension.dart:401:18)\n#6      new CommandWithTarget.deserialize (package:flutter_driver/src/common/find.dart:32:30)\n#7      new GetText.deserialize (package:flutter_driver/src/common/text.dart:14:64)\n#8      DeserializeCommandFactory.deserializeCommand (package:flutter_driver/src/common/deserialization_factory.dart:49:39)\n#9      FlutterDriverExtension.deserializeCommand (package:flutter_driver/src/extension/extension.dart:421:18)\n#10     FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:365:31)\n#11     BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:855:32)\n<asynchronous suspension>\n",
[debug] [FlutterDriver@89ba (e366c792)]   "type": "_extensionType",
[debug] [FlutterDriver@89ba (e366c792)]   "method": "ext.flutter.driver"
[debug] [FlutterDriver@89ba (e366c792)] }
[debug] [FlutterDriver@89ba (e366c792)]     at FlutterDriver.executeElementCommand (C:\git\qa_customer_app\node_modules\appium-flutter-driver\lib\sessions\observatory.ts:198:11)
[debug] [FlutterDriver@89ba (e366c792)]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[debug] [FlutterDriver@89ba (e366c792)]     at FlutterDriver.getText (C:\git\qa_customer_app\node_modules\appium-flutter-driver\lib\commands\element.ts:4:20)
```
Once it reaches the await driver.getElementText, it fails. I have a whole suite of code using appium-flutter-driver working perfectly up until it reaches that code, so I am pretty sure the cause is in using a find.descendant in a find.descendant. also I tested using a single find.descendant and it works correctly.

**Comment by williampearl** [comment]
Cleaned up, the response from DartVM looks like
```
Uncaught extension error while executing get_text: type 'bool' is not a subtype of type 'String' in type cast\
new LinkedHashMap.from.<anonymous closure> (dart:collection/linked_hash_map.dart:187:26)
_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
new LinkedHashMap.from (dart:collection/linked_hash_map.dart:186:11)
Descendant.deserialize (package:flutter_driver/src/common/find.dart:329:9)
DeserializeFinderFactory.deserializeFinder (package:flutter_driver/src/common/deserialization_factory.dart:32:44)
FlutterDriverExtension.deserializeFinder (package:flutter_driver/src/extension/extension.dart:401:18)
new CommandWithTarget.deserialize (package:flutter_driver/src/common/find.dart:32:30)
new GetText.deserialize (package:flutter_driver/src/common/text.dart:14:64)
DeserializeCommandFactory.deserializeCommand (package:flutter_driver/src/common/deserialization_factory.dart:49:39)
FlutterDriverExtension.deserializeCommand (package:flutter_driver/src/extension/extension.dart:421:18)
FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:365:31)
BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:855:32)\n<asynchronous suspension>\n
```

**Comment by williampearl** [comment]
@KazuCocoa Could you please confirm if using find.descendant in find.descendant is supposed to work as I expected, where I can find widget with key 'history_work_order_item_1', then find.descendant that to find it's Text? Basically I'm trying to find the Text on it like history_work_order_item_1->WorkOrderStatusIndicator->Text. This is necessary because I have a list of history_work_order_item's and GetText can only work on one widget at a time. 
If this is a bug in appium-flutter-driver I don't mind spending time fixing it, I just don't want to waste time if it is not intended behavior.
Thanks!

**Comment by KazuCocoa** [comment]
I'm not so familiar with flutter_driver internal, but basically this driver sends flutter_driver command to the Dart VM directly. For example https://api.flutter.dev/flutter/flutter_driver/Descendant-class.html, so the behavior also depends on it.


I created like below change in flutter's basic sample app.
```
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          key: Key('key-counter-parent'), // To pvidide a key to detect the elemenet
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              key: Key('key-counter'),
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
```

Then, below query shown `0`, that was `text` in `key: Key('key-counter')`.
```
parent = by_value_key 'key-counter-parent'
counter_key = by_value_key 'key-counter'
counter = by_descendant(
  serialized_finder: parent,
  matching: counter_key
)
counter = ::Appium::Flutter::Element.new(driver, finder: number)
counter.text  # => 0 which is "text" in "key-counter'"
```

The render tree as a reference
https://gist.github.com/KazuCocoa/44c64eee864c2b0afc6256137874b089 is the rendertree

**Comment by williampearl** [comment]
@KazuCocoa, I spent some time debugging tonight and pulled the flutter repo for 3.3.10, which is what version I was getting the error at. Anyways, after some debugging I managed to get it to correctly deserialize by turning all booleans in the JSON into strings. This makes sense when looking at the Descendant.deserialize function in flutter_driver:
```dart
   /// Deserializes the finder from JSON generated by [serialize].
  static Descendant deserialize(Map<String, String> json, DeserializeFinderFactory finderFactory) {
    final Map<String, String> jsonOfMatcher =
        Map<String, String>.from(jsonDecode(json['of']!) as Map<String, dynamic>);
    final Map<String, String> jsonMatchingMatcher =
        Map<String, String>.from(jsonDecode(json['matching']!) as Map<String, dynamic>);
    return Descendant(
      of: finderFactory.deserializeFinder(jsonOfMatcher),
      matching: finderFactory.deserializeFinder(jsonMatchingMatcher),
      matchRoot: json['matchRoot'] == 'true',
      firstMatchOnly: json['firstMatchOnly'] == 'true',
    );
  }}
```
This is the particular line which was erroring:
```dart
 final Map<String, String> jsonMatchingMatcher =
        Map<String, String>.from(jsonDecode(json['matching']!) as Map<String, dynamic>);
```
It reads the JSON, finds the boolean, then tries to cast a boolean to a string, hence the error. 
I changed the JSON to: 
```
{
    'command': 'get_text',
    'finderType': 'Descendant',
    'firstMatchOnly': 'true',
    'matching': '{\"finderType\":\"Descendant\",\"firstMatchOnly\":\"true\",\"matchRoot\":\"false\",\"of\":\"{\\\"finderType\\\":\\\"ByType\\\",\\\"type\\\":\\\"WorkOrderStatusIndicator\\\"}\",\"matching\":\"{\\\"finderType\\\":\\\"ByType\\\",\\\"type\\\":\\\"Text\\\"}\"}',
    'matchRoot': 'false',
    'of': '{\"finderType\":\"ByValueKey\",\"keyValueString\":\"history_work_order_item_1\",\"keyValueType\":\"String\"}'
}
```
Which allowed this test I wrote in `packages\flutter_driver\test\src\real_tests\find_test.dart` to pass:
```dart
  test('Descendant in descendant finder deserialize', () {
    final Map<String, String> serialized = <String, String>{
      'command': 'get_text',
      'finderType': 'Descendant',
      'firstMatchOnly': 'true',
      'matching': '{\"finderType\":\"Descendant\",\"firstMatchOnly\":\"true\",\"matchRoot\":\"false\",\"of\":\"{\\\"finderType\\\":\\\"ByType\\\",\\\"type\\\":\\\"WorkOrderStatusIndicator\\\"}\",\"matching\":\"{\\\"finderType\\\":\\\"ByType\\\",\\\"type\\\":\\\"Text\\\"}\"}',
      'matchRoot': 'false',
      'of': '{\"finderType\":\"ByValueKey\",\"keyValueString\":\"history_work_order_item_1\",\"keyValueType\":\"String\"}'
    };
    final Descendant a = Descendant.deserialize(serialized, fakeDeserialize);
    expect(a.of, isA<ByValueKey>());
    expect(a.matching, isA<Descendant>());
    expect(a.matchRoot, isFalse);
    expect(a.firstMatchOnly, isTrue);
  });
```
To me, this looks like we should just always pass in the booleans as strings.
Please let me know what you make of it.
Thanks!

**Comment by KazuCocoa** [comment]
interesting... thanks.

I haven't tested well (since the original implementation was different person, I followed that), but it seems like serializing with string could be more proper for the latest spec. Let me take a look https://github.com/appium/appium-flutter-driver/issues/586#issuecomment-1754113891 again.

If so, the finder libraries should handle properly

**Comment by KazuCocoa** [comment]
I confirmed these match_root and first_match_only should be string especially they are nested. So the client finder should fix that

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-flutter-driver/tree/main/finder they have the string value converting in this repo's finders. User user-facing code has no changes.

**Comment by williampearl** [comment]
Thank you for the update @KazuCocoa. Running with the update solved this issue for me.

**Comment by AYASGray** [comment]
@williampearl @KazuCocoa I'm reading this thread with great interest - I updated to 2.2.4 but I still see this issue when I try to do anything with an element that I acquired as a descendant of a descendant - do I need to do something else besides get the latest to get this fix?

**Comment by AYASGray** [comment]
Actually - I figured it out - you have to update the appium-flutter-finder in the package.json to 0.2.0, run npm install to get it, and it works.
