### ISSUE TITLE
driver.activateApp method has not yet been implemented when running through IOS device

### ISSUE THREAD

**Issue by Tegardoa** [appium/appium-flutter-driver#641]
Hi All,
I'm facing issue right now related to `driver.activateApp` in IOS device.
my package.json contains:
```
"appium-flutter-driver": "^2.2.4",
"appium-uiautomator2-driver": "^2.34.2",
"appium-xcuitest-driver": "^5.12.2",
```
In wdio config file, I declare hook like this:

```
beforeSession: function (config, capabilities, specs, cid) {
      global.isFirstLaunch = true;
    },

beforeScenario: async function (world, context) {
      if (global.isFirstLaunch) {
        global.isFirstLaunch = false;
      } else {
        await driver.switchContext('NATIVE_APP');
        await driver.removeApp(appCapabilities["appium:bundleId"]); 
        await driver.installApp(appCapabilities["appium:app"]);
        await driver.switchContext('FLUTTER');
        await driver.activateApp(appCapabilities["appium:bundleId"]);
      }
    },

afterScenario: async function (world, result, context) {
      await driver.switchContext('NATIVE_APP');
      await driver.terminateApp(appCapabilities["appium:bundleId"]);
    },
```

When I tried to start the automation, in the next scenario I got error that said `Method has not yet been implemented` with detail:
```
2023-12-17 04:14:39:030 - [debug] [FlutterDriver@ab5c (d28a79fd)] Calling AppiumDriver.activateApp() with args: ["id.app.beta",null,null,null,"d28a79fd-5357-4bf0-8604-729e6f2f5c40"]
2023-12-17 04:14:39:031 - [AppiumDriver@3458] Plugins which can handle cmd 'activateApp': images
2023-12-17 04:14:39:032 - [AppiumDriver@3458] Plugin images is now handling cmd 'activateApp'
2023-12-17 04:14:39:032 - [AppiumDriver@3458] Executing default handling behavior for command 'activateApp'
2023-12-17 04:14:39:032 - [debug] [FlutterDriver] Executing Flutter driver command 'activateApp'
2023-12-17 04:14:39:042 - [debug] [FlutterDriver@ab5c (d28a79fd)] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
2023-12-17 04:14:39:043 - [debug] [FlutterDriver@ab5c (d28a79fd)]     at FlutterDriver.executeCommand (/nix/store/jgs9a0c0gkz197b7nwvb4ckr2ic8d60n-appium-2.0.0/packages/appium/flutter/1.9.0/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:120:13)
2023-12-17 04:14:39:043 - [debug] [FlutterDriver@ab5c (d28a79fd)]     at runMicrotasks (<anonymous>)
2023-12-17 04:14:39:043 - [debug] [FlutterDriver@ab5c (d28a79fd)]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2023-12-17 04:14:39:043 - [debug] [FlutterDriver@ab5c (d28a79fd)]     at FlutterDriver.executeCommand (/nix/store/jgs9a0c0gkz197b7nwvb4ckr2ic8d60n-appium-2.0.0/packages/appium/flutter/1.9.0/node_modules/appium-flutter-driver/lib/driver.ts:146:6)
2023-12-17 04:14:39:043 - [debug] [FlutterDriver@ab5c (d28a79fd)]     at defaultBehavior (/nix/store/jgs9a0c0gkz197b7nwvb4ckr2ic8d60n-appium-2.0.0/packages/appium/lib/appium.js:602:14)
2023-12-17 04:14:39:043 - [debug] [FlutterDriver@ab5c (d28a79fd)]     at ImageElementPlugin.handle (/nix/store/jgs9a0c0gkz197b7nwvb4ckr2ic8d60n-appium-2.0.0/packages/appium/flutter/1.9.0/node_modules/@appium/images-plugin/lib/plugin.js:77:12)
2023-12-17 04:14:39:043 - [debug] [FlutterDriver@ab5c (d28a79fd)]     at /nix/store/jgs9a0c0gkz197b7nwvb4ckr2ic8d60n-appium-2.0.0/packages/appium/lib/appium.js:647:16
2023-12-17 04:14:39:043 - [debug] [FlutterDriver@ab5c (d28a79fd)]     at AppiumDriver.executeWrappedCommand (/nix/store/jgs9a0c0gkz197b7nwvb4ckr2ic8d60n-appium-2.0.0/packages/appium/lib/appium.js:680:16)
2023-12-17 04:14:39:043 - [debug] [FlutterDriver@ab5c (d28a79fd)]     at AppiumDriver.executeCommand (/nix/store/jgs9a0c0gkz197b7nwvb4ckr2ic8d60n-appium-2.0.0/packages/appium/lib/appium.js:609:17)
2023-12-17 04:14:39:043 - [debug] [FlutterDriver@ab5c (d28a79fd)]     at asyncHandler (/nix/store/jgs9a0c0gkz197b7nwvb4ckr2ic8d60n-appium-2.0.0/packages/base-driver/lib/protocol/protocol.js:313:19)
2023-12-17 04:14:39:045 - [HTTP] <-- POST /wd/hub/session/d28a79fd-5357-4bf0-8604-729e6f2f5c40/appium/device/activate_app 405 32 ms - 1464
2023-12-17 04:14:39:045 - [HTTP] 
2023-12-17 04:14:39:397 - [HTTP] --> POST /wd/hub/session/d28a79fd-5357-4bf0-8604-729e6f2f5c40/appium/device/activate_app
2023-12-17 04:14:39:398 - [HTTP] {"appId":"id.app.beta"}
2023-12-17 04:14:39:400 - [debug] [FlutterDriver@ab5c (d28a79fd)] Calling AppiumDriver.activateApp() with args: ["id.app.beta",null,null,null,"d28a79fd-5357-4bf0-8604-729e6f2f5c40"]
2023-12-17 04:14:39:400 - [AppiumDriver@3458] Plugins which can handle cmd 'activateApp': images
2023-12-17 04:14:39:400 - [AppiumDriver@3458] Plugin images is now handling cmd 'activateApp'
2023-12-17 04:14:39:400 - [AppiumDriver@3458] Executing default handling behavior for command 'activateApp'
2023-12-17 04:14:39:400 - [debug] [FlutterDriver] Executing Flutter driver command 'activateApp'
2023-12-17 04:14:39:402 - [debug] [FlutterDriver@ab5c (d28a79fd)] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
2023-12-17 04:14:39:402 - [debug] [FlutterDriver@ab5c (d28a79fd)]     at FlutterDriver.executeCommand (/nix/store/jgs9a0c0gkz197b7nwvb4ckr2ic8d60n-appium-2.0.0/packages/appium/flutter/1.9.0/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.js:120:13)
2023-12-17 04:14:39:402 - [debug] [FlutterDriver@ab5c (d28a79fd)]     at runMicrotasks (<anonymous>)
2023-12-17 04:14:39:402 - [debug] [FlutterDriver@ab5c (d28a79fd)]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2023-12-17 04:14:39:402 - [debug] [FlutterDriver@ab5c (d28a79fd)]     at FlutterDriver.executeCommand (/nix/store/jgs9a0c0gkz197b7nwvb4ckr2ic8d60n-appium-2.0.0/packages/appium/flutter/1.9.0/node_modules/appium-flutter-driver/lib/driver.ts:146:6)
2023-12-17 04:14:39:402 - [debug] [FlutterDriver@ab5c (d28a79fd)]     at defaultBehavior (/nix/store/jgs9a0c0gkz197b7nwvb4ckr2ic8d60n-appium-2.0.0/packages/appium/lib/appium.js:602:14)
2023-12-17 04:14:39:402 - [debug] [FlutterDriver@ab5c (d28a79fd)]     at ImageElementPlugin.handle (/nix/store/jgs9a0c0gkz197b7nwvb4ckr2ic8d60n-appium-2.0.0/packages/appium/flutter/1.9.0/node_modules/@appium/images-plugin/lib/plugin.js:77:12)
2023-12-17 04:14:39:402 - [debug] [FlutterDriver@ab5c (d28a79fd)]     at /nix/store/jgs9a0c0gkz197b7nwvb4ckr2ic8d60n-appium-2.0.0/packages/appium/lib/appium.js:647:16
2023-12-17 04:14:39:402 - [debug] [FlutterDriver@ab5c (d28a79fd)]     at AppiumDriver.executeWrappedCommand (/nix/store/jgs9a0c0gkz197b7nwvb4ckr2ic8d60n-appium-2.0.0/packages/appium/lib/appium.js:680:16)
2023-12-17 04:14:39:402 - [debug] [FlutterDriver@ab5c (d28a79fd)]     at AppiumDriver.executeCommand (/nix/store/jgs9a0c0gkz197b7nwvb4ckr2ic8d60n-appium-2.0.0/packages/appium/lib/appium.js:609:17)
2023-12-17 04:14:39:403 - [debug] [FlutterDriver@ab5c (d28a79fd)]     at asyncHandler (/nix/store/jgs9a0c0gkz197b7nwvb4ckr2ic8d60n-appium-2.0.0/packages/base-driver/lib/protocol/protocol.js:313:19)
2023-12-17 04:14:39:403 - [HTTP] <-- POST /wd/hub/session/d28a79fd-5357-4bf0-8604-729e6f2f5c40/appium/device/activate_app 405 6 ms - 1464
```
It only happens when I run through IOS device, with the same hook file when I run through android device, the issue never occurs.
Detail appium log android device:
```
2023-12-17 04:38:28:769 - [HTTP] [HTTP] --> POST /wd/hub/session/996477f4-cef8-444b-ae6e-c59f547628c2/appium/device/activate_app
2023-12-17 04:38:28:769 - [HTTP] [HTTP] {"appId":"com.app.beta"}
2023-12-17 04:38:28:769 - [debug] [FlutterDriver@7e98 (996477f4)] [FlutterDriver@7e98 (996477f4)] Calling AppiumDriver.activateApp() with args: ["com.app.beta",null,null,null,"996477f4-cef8-444b-ae6e-c59f547628c2"]
2023-12-17 04:38:28:769 - [debug] [AppiumDriver@f259] [AppiumDriver@f259] Clearing new command timeout pre-emptively since plugin(s) will handle this command
2023-12-17 04:38:28:770 - [AppiumDriver@f259] [AppiumDriver@f259] Plugins which can handle cmd 'activateApp': images
2023-12-17 04:38:28:770 - [AppiumDriver@f259] [AppiumDriver@f259] Plugin images is now handling cmd 'activateApp'
2023-12-17 04:38:28:770 - [AppiumDriver@f259] [AppiumDriver@f259] Executing default handling behavior for command 'activateApp'
2023-12-17 04:38:28:770 - [debug] [FlutterDriver] [FlutterDriver] Executing Flutter driver command 'activateApp'
2023-12-17 04:38:28:770 - [debug] [AndroidUiautomator2Driver@20b3 (b6811ab9)] [AndroidUiautomator2Driver@20b3 (b6811ab9)] Activating 'com.app.beta'
```
Is there any suggestion to resolve error like this ? I really appreciate your guidance. Thanks All.

**Comment by KazuCocoa** [comment]
It looks like `images` plugin handles the `activateApp` before reaching driver.


```
2023-12-17 04:14:39:031 - [AppiumDriver@3458] Plugins which can handle cmd 'activateApp': images
2023-12-17 04:14:39:032 - [AppiumDriver@3458] Plugin images is now handling cmd 'activateApp'
```

What version of Appium server did you use? What about using the latest one?
Possibly, it needs to be reported to appium repository to fix plugins/drivers resolving method.

**Comment by KazuCocoa** [comment]
Could you attach the full appium log?

The `Executing Flutter driver command 'activateApp'` could match with https://github.com/appium/appium-flutter-driver/blob/330ab4b9745b36d84c3865c5d171eeb03cc6d558/driver/lib/driver.ts#L147-L150 , but maybe something was wrong.

**Comment by Tegardoa** [comment]
@KazuCocoa 
> What version of Appium server did you use? What about using the latest one?

I'm using 2.0.1.

Here it's for the full appium logs:
[ios-appium-logs.txt](https://github.com/appium/appium-flutter-driver/files/13695199/ios-appium-logs.txt)

**Comment by KazuCocoa** [comment]
It looks like the session created appium flutter driver 1.9.0.

```
2023-12-17 04:13:47:319 - [Appium] Attempting to find matching driver for automationName 'flutter' and platformName 'iOS'
2023-12-17 04:13:47:319 - [Appium] The 'flutter' driver was installed and matched caps.
2023-12-17 04:13:47:319 - [Appium] Will require it at /usr/local/.browserstack/appium_2.0.0_bstack/packages/appium/flutter/1.9.0/node_modules/appium-flutter-driver
2023-12-17 04:13:47:319 - [debug] [Appium] Requiring driver at /usr/local/.browserstack/appium_2.0.0_bstack/packages/appium/flutter/1.9.0/node_modules/appium-flutter-driver
2023-12-17 04:13:47:319 - [AppiumDriver@3458] Appium v2.0.0-beta.35 creating new FlutterDriver (v1.9.0) session
2023-12-17 04:13:47:319 - [AppiumDriver@3458] Checking BaseDriver versions for Appium and FlutterDriver
2023-12-17 04:13:47:319 - [AppiumDriver@3458] Appium's BaseDriver version is 8.5.3
2023-12-17 04:13:47:319 - [AppiumDriver@3458] FlutterDriver's BaseDriver version is 8.7.3
```

What's about the log for the working Android?

**Comment by Tegardoa** [comment]
@KazuCocoa 
Here's the log for android:
[android-appium-logs.txt](https://github.com/appium/appium-flutter-driver/files/13695399/android-appium-logs.txt)

it seems, it creates different version:
```
2023-12-17 08:34:18:910 - [AppiumDriver@84b3] [AppiumDriver@84b3] Appium v2.0.1 creating new FlutterDriver (v1.18.1) session
````
Any clue why did it happen ?

**Comment by KazuCocoa** [comment]
i don't know.

On your env, Android's Appium was started 
```
2023-12-17 08:34:18:909 - [Appium] [Appium] The 'flutter' driver was installed and matched caps.
2023-12-17 08:34:18:909 - [Appium] [Appium] Will require it at /usr/local/.browserstack/appium_2.0.1_bstack/packages/appium/flutter/1.18.1/node_modules/appium-flutter-driver
2023-12-17 08:34:18:909 - [debug] [Appium] [Appium] Requiring driver at /usr/local/.browserstack/appium_2.0.1_bstack/packages/appium/flutter/1.18.1/node_modules/appium-flutter-driver
2023-12-17 08:34:18:910 - [AppiumDriver@84b3] [AppiumDriver@84b3] Appium v2.0.1 creating new FlutterDriver (v1.18.1) session
2023-12-17 08:34:18:910 - [AppiumDriver@84b3] [AppiumDriver@84b3] Checking BaseDriver versions for Appium and FlutterDriver
```

but iOS was:

```
2023-12-17 04:13:47:319 - [Appium] The 'flutter' driver was installed and matched caps.
2023-12-17 04:13:47:319 - [Appium] Will require it at /usr/local/.browserstack/appium_2.0.0_bstack/packages/appium/flutter/1.9.0/node_modules/appium-flutter-driver
2023-12-17 04:13:47:319 - [debug] [Appium] Requiring driver at /usr/local/.browserstack/appium_2.0.0_bstack/packages/appium/flutter/1.9.0/node_modules/appium-flutter-driver
2023-12-17 04:13:47:319 - [AppiumDriver@3458] Appium v2.0.0-beta.35 creating new FlutterDriver (v1.9.0) session
2023-12-17 04:13:47:319 - [AppiumDriver@3458] Checking BaseDriver versions for Appium and FlutterDriver
```

so they launched different Appium and the dependencies, I guess.

**Comment by KazuCocoa** [comment]
Please ask the browserstack's support team
