### ISSUE TITLE
 Could not find 'apksigner.jar

### ISSUE THREAD

**Issue by Potterjr** [appium/appium-flutter-driver#678]
Event 'newSessionStarted' logged at 1712112110259 (09:41:50 GMT+0700)
[AppiumDriver@2f25] Encountered internal error running command: Error: Cannot verify the signature of 'C:\Users\poto1\node_modules\appium-flutter-driver\node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk'. Original error: Could not find 'apksigner.jar' in ["C:\\Users\\poto1\\AppData\\Local\\Android\\Sdk\\platform-tools\\platform-tools\\apksigner.jar","C:\\Users\\poto1\\AppData\\Local\\Android\\Sdk\\platform-tools\\emulator\\apksigner.jar","C:\\Users\\poto1\\AppData\\Local\\Android\\Sdk\\platform-tools\\cmdline-tools\\latest\\bin\\apksigner.jar","C:\\Users\\poto1\\AppData\\Local\\Android\\Sdk\\platform-tools\\tools\\apksigner.jar","C:\\Users\\poto1\\AppData\\Local\\Android\\Sdk\\platform-tools\\tools\\bin\\apksigner.jar","C:\\Users\\poto1\\AppData\\Local\\Android\\Sdk\\platform-tools\\apksigner.jar"]. Do you have Android Build Tools installed at 'C:\Users\poto1\AppData\Local\Android\Sdk\platform-tools'?
[AppiumDriver@2f25]     at ADB.checkApkCert (C:\Users\poto1\node_modules\appium-flutter-driver\node_modules\appium-uiautomator2-driver\node_modules\appium-adb\lib\tools\apk-signing.js:320:11)
[AppiumDriver@2f25]     at UiAutomator2Server.prepareServerPackage (C:\Users\poto1\node_modules\appium-flutter-driver\node_modules\appium-uiautomator2-driver\lib\uiautomator2.js:89:9)

![image](https://github.com/appium/appium-flutter-driver/assets/119689321/5dec472c-c718-49fa-95bc-bac565126f6b)

**Comment by KazuCocoa** [comment]
Usually it is in build tools. What name of `apksigner.jar` is in your build tools directory?

**Comment by Potterjr** [comment]
this is in my directory in \Android\Sdk\build-tools\35.0.0-rc2\lib
![image](https://github.com/appium/appium-flutter-driver/assets/119689321/2939534f-b424-4aaf-91ca-c6525327d4b9)
I have apksigner.jar but I don't know why did not find 'apksigner.jar'

**Comment by KazuCocoa** [comment]
Could you share the full appium log as well?
I'd like to check around:
https://github.com/appium/appium-adb/blob/16aad1ae88be216e170be01e0c11e976be5db576/lib/helpers.js#L476
https://github.com/appium/appium-adb/blob/16aad1ae88be216e170be01e0c11e976be5db576/lib/tools/system-calls.js#L98-L140
behavior on your env.
