### ISSUE TITLE
Ruby appium_flutter_finder error: undefined method `bridge' for Appium

### ISSUE THREAD

**Issue by kevin-roe** [appium/appium-flutter-driver#721]
When I try to create an `Appium::Flutter::Element`, I get this error: 

```
/Users/kevin.roe/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/appium_flutter_finder-0.7.1/lib/appium_flutter_finder.rb:15:in `initialize': undefined method `bridge' for #<Appium::Driver:0x000000010492c8b8 @core=#<Appium::Core::Driver:0x000000010492c728 @delegate_target=#<Appium::Core::Driver:0x000000010492c728 ...>, @automation_name=:xcuitest, @custom_url="http://127.0.0.1:4723/wd/hub", @caps=#<Appium::Core::Base::Capabilities:0x000000010492c2c8 @capabilities={:platformName=>:ios, :udid=>"C942CC95-20A0-4348-A88C-692811C1F4AF", :automationName=>"XCUITest", :bundleId=>"com.example.myDemoAppFlutter"}>, @enable_idempotency_header=true, @default_wait=nil, @port=4723, @wait_timeout=30, @wait_interval=0.5, @listener=nil, @direct_connect=true, @device=:ios, @http_client=#<Appium::Http::Default:0x0000000104b7b240 @open_timeout=nil, @read_timeout=nil, @additional_headers={}, @server_url=#<URI::HTTP http://127.0.0.1:4723/wd/hub/>, @common_headers={"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.23.0 (ruby macosx)"}, @proxy=nil, @http=#<Net::HTTP 127.0.0.1:4723 open=true>>, @driver=#<Appium::Core::Base::Driver:0x..fa44ac01205956150 browser=:"">>, @caps=#<Appium::Core::Base::Capabilities:0x000000010492c2c8 @capabilities={:platformName=>:ios, :udid=>"C942CC95-20A0-4348-A88C-692811C1F4AF", :automationName=>"XCUITest", :bundleId=>"com.example.myDemoAppFlutter"}>, @custom_url=nil, @default_wait=0, @appium_port=4723, @appium_wait_timeout=30, @appium_wait_interval=0.5, @listener=nil, @appium_device=:ios, @automation_name=:xcuitest, @appium_debug=false, @sauce=#<Appium::SauceLabs:0x0000000104b83b70 @username=nil, @access_key=nil, @endpoint="ondemand.saucelabs.com:443/wd/hub">, @sauce_username=nil, @sauce_access_key=nil, @sauce_endpoint="ondemand.saucelabs.com:443/wd/hub", @driver=#<Appium::Core::Base::Driver:0x..fa44ac01205956150 browser=:"">, @http_client=#<Appium::Http::Default:0x0000000104b7b240 @open_timeout=nil, @read_timeout=nil, @additional_headers={}, @server_url=#<URI::HTTP http://127.0.0.1:4723/wd/hub/>, @common_headers={"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"selenium/4.23.0 (ruby macosx)"}, @proxy=nil, @http=#<Net::HTTP 127.0.0.1:4723 open=true>>, @appium_server_status={"ready"=>true, "message"=>"The server is ready to accept new connections", "build"=>{"version"=>"2.11.2"}}> (NoMethodError)

        @bridge = driver.bridge
                        ^^^^^^^
```

This is my code: 

```ruby
require 'appium_lib'
require 'appium_flutter_finder'

class Tester
  include Appium::Flutter::Finder

  def initialize
    caps = {
      platformName: :ios,
      udid: "C942CC95-20A0-4348-A88C-692811C1F4AF",
      automationName: "Flutter",
      bundleId: "com.example.myDemoAppFlutter"
    }

    @driver = Appium::Driver.new({ caps: caps, global_driver: true })
  end

  def go
    @driver.start_driver
    element = by_semantics_label("Increment Button")
    Appium::Flutter::Element.new(@driver, finder: element)
  end
end

Tester.new.go
```

I am using the Saucelabs demo flutter app, but I don't get far enough for that to matter.  I also tried instantiating a remote driver through Browserstack using one off our production app tests. (in case the Selenium grid created `@driver.bridge`), and then trying to instantiate an `Appium::Flutter::Element`, but I got the same error.  Any help would be appreciated!

**Comment by KazuCocoa** [comment]
In your case, `Appium::Flutter::Element.new(@driver.driver, finder: element)` would work.

I usually use `appium_lib_core` like https://github.com/appium/appium-flutter-driver/blob/main/example/ruby/example_sample2.rb , btw.

**Comment by kevin-roe** [comment]
So, making that change did create an `Appium::Flutter::Element`.  However, when i added a `.click` command, I got this error:

```ruby
# Updated code

@driver.start_driver
element = by_semantics_label("Increment Button")
Appium::Flutter::Element.new(@driver.driver, finder: element).click
```

```
# Error Message

UnknownError: An unknown server-side error occurred while processing the command. Original error: {"code":-32000,"message":"Server error","data":{"details":"{\"exception\":\"UnimplementedError: tap is not implemented\",\"stack\":\"#0      _IOCallbackManager.callback (package:integration_test/src/_callback_io.dart:47:9)\\n#1      IntegrationTestWidgetsFlutterBinding.callback (package:integration_test/integration_test.dart:207:28)\\n#2      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:941:32)\\n<asynchronous suspension>\\n#3      _runExtension.<anonymous closure> (dart:developer-patch/developer.dart:112:11)\\n<asynchronous suspension>\\n\",\"method\":\"ext.flutter.driver\"}"}}
    at getResponseForW3CError (/Users/kevin.roe/.asdf/installs/nodejs/18.8.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1145:9)
    at asyncHandler (/Users/kevin.roe/.asdf/installs/nodejs/18.8.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:485:57): Selenium::WebDriver::Error::WebDriverError
```

I then tried to update my code to use `appium_lib_core` and got the same error:

```ruby
require 'appium_lib_core'
require 'appium_flutter_finder'

class Tester
  include Appium::Flutter::Finder

  def initialize
    caps = {
      caps: {
        platformName: :ios,
        udid: "C942CC95-20A0-4348-A88C-692811C1F4AF",
        automationName: "Flutter",
        bundleId: "com.example.myDemoAppFlutter"
      },
      appium_lib: {
        export_session: true,
        wait_timeout: 20,
        wait_interval: 1
      }
    }

    @core = ::Appium::Core.for(caps)
    @driver = @core.start_driver server_url: 'http://localhost:4723'
  end

  def go
    e = by_semantics_label("Increment Button")
    element = Appium::Flutter::Element.new(@driver, finder: e)
    element.click
  end
end

Tester.new.go
```

**Comment by KazuCocoa** [comment]
The error came from the DartVM/Flutter side, not from this driver. I would check `flutter_driver` deps on your dependency https://github.com/appium/appium-flutter-driver?tab=readme-ov-file#usage-and-requirement

**Comment by kevin-roe** [comment]
Ah interesting.  Yeah, I had the app configured incorrectly.  Thank you!
