### ISSUE TITLE
No Chromedriver found that can automate Chrome '130.0.6723'

### ISSUE THREAD

**Issue by thuonglai** [appium/appium-flutter-driver#752]
Hi @KazuCocoa. I switch context and has this error "No Chromedriver found that can automate Chrome '130.0.6723'". It maybe is same this issue https://github.com/appium/appium-flutter-driver/issues/438. 
Can you update uia2 driver for it? Thank you

**Comment by KazuCocoa** [comment]
Please attached the full appium server log. What UIA2 driver version do you need? This latest driver has UIA2 driver v3.7.6.

**Comment by thuonglai** [comment]
@KazuCocoa This is my log appium https://gist.github.com/thuonglai/d766e87222883423e3eae14e8157fd78

**Comment by thuonglai** [comment]
@KazuCocoa This is my appium log https://gist.github.com/thuonglai/d766e87222883423e3eae14e8157fd78

**Comment by KazuCocoa** [comment]
The primary reason was your environment failed to get content from `https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json` which is necessary for auto download. Can your environment access to the URL and get the contents?

```
[cb4cd845][Chromedriver@ed92] The following Chromedriver executables were found:
[cb4cd845][Chromedriver@ed92]     '/Users/axlehire/node_modules/appium-flutter-driver/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver-mac-arm64_v127.0.6533.88' (version '127.0.6533.88', minimum Chrome version '127.0.6533')
[cb4cd845][Chromedriver@ed92]     '/Users/axlehire/node_modules/appium-flutter-driver/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver_mac_arm64_v114.0.5735.90' (version '114.0.5735.90', minimum Chrome version '114.0.5735')
[cb4cd845][Chromedriver@ed92] Browser version in the supplied details: Chrome/130.0.6723.86
[cb4cd845][Chromedriver@ed92] Found Chrome bundle 'undefined' version '130.0.6723'
[cb4cd845][ChromedriverStorageClient] AxiosError: timeout of 15000ms exceeded
    at RedirectableRequest.handleRequestTimeout (/Users/axlehire/node_modules/appium-flutter-driver/node_modules/appium-uiautomator2-driver/node_modules/axios/lib/adapters/http.js:657:16)
    at RedirectableRequest.emit (node:events:527:28)
    at Timeout.<anonymous> (/Users/axlehire/node_modules/appium-flutter-driver/node_modules/appium-uiautomator2-driver/node_modules/follow-redirects/index.js:210:12)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
    at Axios.request (/Users/axlehire/node_modules/appium-flutter-driver/node_modules/appium-uiautomator2-driver/node_modules/axios/lib/core/Axios.js:45:41)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:533:9)
    at processTimers (node:internal/timers:507:7)
    at retrieveData (/Users/axlehire/node_modules/appium-flutter-driver/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/lib/utils.js:92:5)
    at retrieveResponseSafely (/Users/axlehire/node_modules/appium-flutter-driver/node_modules/appium-uiautomator2-driver/node_modules/appium-chromedriver/lib/storage-client/storage-client.js:73:16)
[cb4cd845][ChromedriverStorageClient] Cannot retrieve Chromedrivers info from https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json. Make sure this URL is accessible from your network. Original error: timeout of 15000ms exceeded
```

**Comment by thuonglai** [comment]
@KazuCocoa  Yes. I can access this link and get content
