### ISSUE TITLE
🐞 bug: Screenshot 500 for flutter driver

### ISSUE THREAD

**Issue by Badhron** [appium/appium-flutter-driver#759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Appium Version

2.13.1

### Appium Host Type

Command Line

### Is this issue reproducible using the latest components?

- [X] I confirm the issue is still reproducible with the latest component versions

### Current Behavior

![Screenshot 2024-12-27 at 14 32 25](https://github.com/user-attachments/assets/753828bf-55d1-4e47-9458-e9d60e4d5708)
![Screenshot 2024-12-27 at 14 33 15](https://github.com/user-attachments/assets/0f0ab30f-54fb-44f5-9707-9a639ed213be)

Appium Inspector Capabilities as follows : 
{
  "platformName": "iOS",
  "appium:platformVersion": "18.1.1",
  "appium:udid": "",
  "appium:automationName": "Flutter",
  "appium:xcodeOrgId": "",
  "appium:xcodeSigningId": "iPhone Developer",
  "appium:bundleId": "",
  "appium:showXcodeLog": true,
}

Error : 
```
[2fc648d0][FlutterDriver@dd93] Calling AppiumDriver.getScreenshot() with args: ["2fc648d0-92dd-443a-b3b9-40038eaa097b"]
[2fc648d0][FlutterDriver] Executing Flutter driver command 'getScreenshot'
[2fc648d0][FlutterDriver@dd93] [ '{"code":-32000,"message":"Could not capture image screenshot."}' ]
[2fc648d0][FlutterDriver@dd93] Encountered internal error running command: Error: {"code":-32000,"message":"Could not capture image screenshot."}
    at Object.errorWithException (/Users/berkinmecik/node_modules/@appium/support/lib/logging.js:41:45)
    at Object.errorAndThrow (/Users/berkinmecik/node_modules/@appium/support/lib/logging.js:44:18)
    at IsolateSocket.socket.call (/Users/berkinmecik/node_modules/appium-flutter-driver/lib/sessions/observatory.ts:64:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at FlutterDriver.getScreenshot (/Users/berkinmecik/node_modules/appium-flutter-driver/lib/commands/screen.ts:4:20)
[2fc648d0][HTTP] <-- GET /session/2fc648d0-92dd-443a-b3b9-40038eaa097b/screenshot 500 14 ms - 644
```

- XCUITest doesnt have this kind of problem and i can observe app but when i use flutter throws this error. 

### Expected Behavior

to be able to observe app at appium inspector

### Environment Details

```
"node": {
    "version": "v20.18.1",
    "arch": "arm64",
    "cwd": "/Users/berkinmecik",
    "argv": [
      "/opt/homebrew/Cellar/node@20/20.18.1/bin/node",
      "/opt/homebrew/bin/appium",
      "--show-debug-info"
    ]
"appium": {
    "location": "/opt/homebrew/lib/node_modules/appium",
    "homedir": "/Users/berkinmecik",
    "build": {
      "version": "2.13.1",
      "git-sha": "",
      "built": "2024-12-15 15:47:40 +0000"
    },
    "drivers": {
      "flutter": {
        "automationName": "Flutter",
        "platformNames": [
          "iOS",
          "Android"
        ],
        "mainClass": "FlutterDriver",
        "doctor": {
          "checks": [
            "./build/lib/doctor/checks.js"
          ]
        },
        "pkgName": "appium-flutter-driver",
        "version": "2.11.0",
        "appiumVersion": "^2.4.1",
        "installType": "npm",
        "installSpec": "appium-flutter-driver@2.11.0",
        "installPath": "/Users/berkinmecik/node_modules/appium-flutter-driver"
      },
      "xcuitest": {
        "automationName": "XCUITest",
        "platformNames": [
          "iOS",
          "tvOS"
        ],
        "mainClass": "XCUITestDriver",
        "scripts": {
          "build-wda": "./scripts/build-wda.js",
          "open-wda": "./scripts/open-wda.js"
        }
```
- Test device : iOS 18.1.1 Real device

### Minimal Reproducible Example

----

**Comment by KazuCocoa** [comment]
Screenshot in Flutter context depends on https://api.flutter.dev/flutter/flutter_driver/FlutterDriver/screenshot.html

Roughly searched the error message in the flutter repository. Maybe below links are related ones. I haven't tracked exact error condition in the flutter repository but at least something occurred in the Flutter later.
https://github.com/flutter/flutter/blob/09a585ba1dd3b856c6a168005ce40553e61f7f2d/engine/src/flutter/shell/common/shell.cc#L1719-L1726
https://github.com/flutter/flutter/blob/09a585ba1dd3b856c6a168005ce40553e61f7f2d/engine/src/flutter/shell/common/shell.cc#L1729-L1746

I guess the system log may have some info for you?

**Comment by Badhron** [comment]
Full log : 

```
2024-12-30 11:07:34:016 - [Appium] Welcome to Appium v2.13.1 (REV 3001afe88112c13b5aafdd92e097680897060881)
        2024-12-30 11:07:34:018 - [Appium] Non-default server args:
        2024-12-30 11:07:34:019 - [Appium] {
address: '127.0.0.1',
logTimestamp: true,
port: 4728
        }
        2024-12-30 11:07:34:019 - [Appium] The autodetected Appium home path: /Users/berkinmecik
2024-12-30 11:07:34:019 - [Appium] Attempting to load driver flutter...
        2024-12-30 11:07:34:019 - [Appium] Attempting to load driver xcuitest...
        2024-12-30 11:07:34:020 - [Appium] Attempting to load driver flutter-integration...
        2024-12-30 11:07:34:020 - [Appium] Requiring driver at /Users/berkinmecik/node_modules/appium-flutter-driver/build/lib/driver.js
2024-12-30 11:07:34:022 - [Appium] Requiring driver at /Users/berkinmecik/node_modules/appium-xcuitest-driver/build/index.js
2024-12-30 11:07:34:022 - [Appium] Requiring driver at /Users/berkinmecik/node_modules/appium-flutter-integration-driver/build/src/driver.js
2024-12-30 11:07:35:652 - [Appium] FlutterDriver has been successfully loaded in 1.633s
2024-12-30 11:07:35:652 - [Appium] XCUITestDriver has been successfully loaded in 1.633s
2024-12-30 11:07:35:652 - [Appium] AppiumFlutterDriver has been successfully loaded in 1.633s
2024-12-30 11:07:35:653 - [Appium] Attempting to load driver uiautomator2...
        2024-12-30 11:07:35:654 - [Appium] Requiring driver at /Users/berkinmecik/node_modules/appium-uiautomator2-driver/build/index.js
2024-12-30 11:07:35:655 - [Appium] AndroidUiautomator2Driver has been successfully loaded in 0.002s
2024-12-30 11:07:35:660 - [Appium] Appium REST http interface listener started on http://127.0.0.1:4728
        2024-12-30 11:07:35:660 - [Appium] Available drivers:
        2024-12-30 11:07:35:661 - [Appium]   - flutter@2.11.0 (automationName 'Flutter')
        2024-12-30 11:07:35:661 - [Appium]   - xcuitest@7.34.1 (automationName 'XCUITest')
        2024-12-30 11:07:35:661 - [Appium]   - flutter-integration@1.1.3 (automationName 'FlutterIntegration')
        2024-12-30 11:07:35:661 - [Appium]   - uiautomator2@3.7.6 (automationName 'UiAutomator2')
        2024-12-30 11:07:35:661 - [Appium] Available plugins:
        2024-12-30 11:07:35:661 - [Appium]   - images@3.0.24
        2024-12-30 11:07:35:661 - [Appium] No plugins activated. Use the --use-plugins flag with names of plugins to activate
2024-12-30 11:07:58:826 - [HTTP] --> POST /session {"capabilities":{"alwaysMatch":{"platformName":"iOS","appium:platformVersion":"18.1.1","appium:udid":"--","appium:automationName":"Flutter","appium:xcodeOrgId":"--","appium:xcodeSigningId":"iPhone Developer","appium:bundleId":"--","appium:showXcodeLog":true,"appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"iOS","appium:platformVersion":"18.1.1","appium:udid":"--","appium:automationName":"Flutter","appium:xcodeOrgId":"--","appium:xcodeSigningId":"iPhone Developer","appium:bundleId":"--","appium:showXcodeLog":true,"appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}}
2024-12-30 11:07:58:828 - [AppiumDriver@44ac] Calling AppiumDriver.createSession() with args: [{"platformName":"iOS","appium:platformVersion":"18.1.1","appium:udid":"--","appium:automationName":"Flutter","appium:xcodeOrgId":"--","appium:xcodeSigningId":"iPhone Developer","appium:bundleId":"--","appium:showXcodeLog":true,"appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"platformName":"iOS","appium:platformVersion":"18.1.1","appium:udid":"--","appium:automationName":"Flutter","appium:xcodeOrgId":"--","appium:xcodeSigningId":"iPhone Developer","appium:bundleId":"--","appium:showXcodeLog":true,"appium:includeSafariInWebviews":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}]
        2024-12-30 11:07:58:829 - [AppiumDriver@44ac] Event 'newSessionRequested' logged at 1735556878829 (14:07:58 GMT+0300 (GMT+03:00))
        2024-12-30 11:07:58:833 - [Appium] Attempting to find matching driver for automationName 'Flutter' and platformName 'iOS'
        2024-12-30 11:07:58:834 - [Appium] The 'flutter' driver was installed and matched caps.
        2024-12-30 11:07:58:834 - [Appium] Will require it at /Users/berkinmecik/node_modules/appium-flutter-driver
2024-12-30 11:07:58:835 - [Appium] Requiring driver at /Users/berkinmecik/node_modules/appium-flutter-driver/build/lib/driver.js
2024-12-30 11:07:58:836 - [AppiumDriver@44ac] Appium v2.13.1 creating new FlutterDriver (v2.11.0) session
2024-12-30 11:07:58:836 - [AppiumDriver@44ac] Checking BaseDriver versions for Appium and FlutterDriver
2024-12-30 11:07:58:836 - [AppiumDriver@44ac] Appium's BaseDriver version is 9.13.1
        2024-12-30 11:07:58:836 - [AppiumDriver@44ac] FlutterDriver's BaseDriver version is 9.11.2
        2024-12-30 11:07:58:838 - [FlutterDriver@573f] undefined
2024-12-30 11:07:58:839 - [FlutterDriver@573f] Creating session with W3C capabilities: {
        "alwaysMatch": {
        "platformName": "iOS",
        "appium:platformVersion": "18.1.1",
        "appium:udid": "--",
        "appium:automationName": "Flutter",
        "appium:xcodeOrgId": "--",
        "appium:xcodeSigningId": "iPhone Developer",
        "appium:bundleId": "--",
        "appium:showXcodeLog": true,
        "appium:includeSafariInWebviews": true,
        "appium:newCommandTimeout": 3600,
        "appium:connectHardwareKeyboard": true
        },
        "firstMatch": [
        {}
        ]
        }
        2024-12-30 11:07:58:842 - [FlutterDriver@573f] The following provided capabilities were not recognized by this driver:
        2024-12-30 11:07:58:842 - [FlutterDriver@573f]   xcodeOrgId
2024-12-30 11:07:58:842 - [FlutterDriver@573f]   xcodeSigningId
2024-12-30 11:07:58:842 - [FlutterDriver@573f]   bundleId
2024-12-30 11:07:58:842 - [FlutterDriver@573f]   showXcodeLog
2024-12-30 11:07:58:842 - [FlutterDriver@573f]   includeSafariInWebviews
2024-12-30 11:07:58:842 - [FlutterDriver@573f]   connectHardwareKeyboard
2024-12-30 11:07:58:842 - [b22392a9][FlutterDriver@573f] Session created with session id: b22392a9-a9d7-4a6a-8401-11ef3e6c9082
2024-12-30 11:07:58:843 - [b22392a9][FlutterDriver@573f] Starting an IOS proxy session
2024-12-30 11:07:58:844 - [b22392a9][XCUITestDriver@f217] undefined
2024-12-30 11:07:58:845 - [b22392a9][XCUITestDriver@f217] Creating session with W3C capabilities: {
        "alwaysMatch": {
        "platformName": "iOS",
        "appium:platformVersion": "18.1.1",
        "appium:udid": "--",
        "appium:automationName": "Flutter",
        "appium:xcodeOrgId": "--",
        "appium:xcodeSigningId": "iPhone Developer",
        "appium:bundleId": "--",
        "appium:showXcodeLog": true,
        "appium:includeSafariInWebviews": true,
        "appium:newCommandTimeout": 3600,
        "appium:connectHardwareKeyboard": true
        },
        "firstMatch": [
        {}
        ]
        }
        2024-12-30 11:07:58:849 - [af38b09d][XCUITestDriver@f217] Session created with session id: af38b09d-73ce-47b7-ad0c-d3858fa17a95
2024-12-30 11:07:58:857 - [af38b09d][XCUITest] Current user: 'berkinmecik'
        2024-12-30 11:07:58:865 - [af38b09d][XCUITestDriver@f217] Available real devices: --
2024-12-30 11:07:58:866 - [af38b09d][XCUITestDriver@f217] Creating iDevice object with udid '--'
        2024-12-30 11:07:58:866 - [af38b09d][XCUITestDriver@f217] Determining device to run tests on: udid: '--', real device: true
        2024-12-30 11:07:58:866 - [af38b09d][XCUITestDriver@f217] Normalized platformVersion capability value '18.1.1' to '18.1'
        2024-12-30 11:07:58:884 - [af38b09d][XCUITestDriver@f217] Event 'xcodeDetailsRetrieved' logged at 1735556878884 (14:07:58 GMT+0300 (GMT+03:00))
        2024-12-30 11:07:58:884 - [af38b09d][XCUITestDriver@f217] Event 'appConfigured' logged at 1735556878884 (14:07:58 GMT+0300 (GMT+03:00))
        2024-12-30 11:07:58:884 - [af38b09d][XCUITestDriver@f217] Event 'resetStarted' logged at 1735556878884 (14:07:58 GMT+0300 (GMT+03:00))
        2024-12-30 11:07:58:884 - [af38b09d][XCUITestDriver@f217] Reset: running ios real device reset flow
2024-12-30 11:07:58:884 - [af38b09d][XCUITestDriver@f217] Event 'resetComplete' logged at 1735556878884 (14:07:58 GMT+0300 (GMT+03:00))
        2024-12-30 11:07:58:885 - [af38b09d][XCUITestDriver@f217] Using WDA path: '/Users/berkinmecik/node_modules/appium-flutter-driver/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent'
        2024-12-30 11:07:58:885 - [af38b09d][XCUITestDriver@f217] Using WDA agent: '/Users/berkinmecik/node_modules/appium-flutter-driver/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
        2024-12-30 11:07:58:891 - [af38b09d][XCUITestDriver@f217] The pyidevice tool is not present in PATH. Skipping crash logs collection for real devices.
        2024-12-30 11:07:59:006 - [af38b09d][XCUITestDriver@f217] Event 'logCaptureStarted' logged at 1735556879006 (14:07:59 GMT+0300 (GMT+03:00))
        2024-12-30 11:07:59:006 - [af38b09d][XCUITestDriver@f217] Setting up real device
2024-12-30 11:07:59:208 - [af38b09d][XCUITestDriver@f217] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
2024-12-30 11:07:59:209 - [af38b09d][DevCon Factory] Requesting connection for device -- on local port 8100, device port 8100
        2024-12-30 11:07:59:209 - [af38b09d][DevCon Factory] Cached connections count: 0
        2024-12-30 11:07:59:210 - [af38b09d][DevCon Factory] Successfully requested the connection for --:8100
        2024-12-30 11:07:59:210 - [af38b09d][XCUITestDriver@f217] Starting WebDriverAgent initialization with the synchronization key 'XCUITestDriver'
        2024-12-30 11:07:59:211 - [af38b09d][WD Proxy] Matched '/status' to command name 'getStatus'
        2024-12-30 11:07:59:211 - [af38b09d][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
        2024-12-30 11:07:59:224 - [af38b09d][WD Proxy] Got response with status 200: {"value":{"build":{"upgradedAt":"1734534191871","version":"8.11.1","time":"Dec 27 2024 13:19:03","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"},"os":{"testmanagerdVersion":65535,"name":"iOS","sdkVersion":"18.0","version":"18.1.1"},"device":"iphone","ios":{"ip":"172.16.110.129"},"message":"WebDriverAgent is ready to accept commands","state":"success","ready":true},"sessionId":null}
        2024-12-30 11:07:59:224 - [af38b09d][XCUITestDriver@f217] Upgrade timestamp of the currently bundled WDA: 1734534191871
        2024-12-30 11:07:59:224 - [af38b09d][XCUITestDriver@f217] Upgrade timestamp of the WDA on the device: 1734534191871
        2024-12-30 11:07:59:224 - [af38b09d][XCUITestDriver@f217] Will reuse previously cached WDA instance at 'http://127.0.0.1:8100/' with 'com.facebook.WebDriverAgentRunner'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
        2024-12-30 11:07:59:225 - [af38b09d][XCUITestDriver@f217] Trying to start WebDriverAgent 1 times with 10000ms interval
2024-12-30 11:07:59:225 - [af38b09d][XCUITestDriver@f217] These values can be customized by changing wdaStartupRetries/wdaStartupRetryInterval capabilities
2024-12-30 11:07:59:225 - [af38b09d][XCUITestDriver@f217] Event 'wdaStartAttempted' logged at 1735556879225 (14:07:59 GMT+0300 (GMT+03:00))
        2024-12-30 11:07:59:225 - [af38b09d][XCUITestDriver@f217] Using provided WebdriverAgent at 'http://127.0.0.1:8100/'
        2024-12-30 11:07:59:225 - [af38b09d][WD Proxy] Matched '/status' to command name 'getStatus'
        2024-12-30 11:07:59:226 - [af38b09d][WD Proxy] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
        2024-12-30 11:07:59:232 - [af38b09d][WD Proxy] Got response with status 200: {"value":{"build":{"upgradedAt":"1734534191871","version":"8.11.1","time":"Dec 27 2024 13:19:03","productBundleIdentifier":"com.facebook.WebDriverAgentRunner"},"os":{"testmanagerdVersion":65535,"name":"iOS","sdkVersion":"18.0","version":"18.1.1"},"device":"iphone","ios":{"ip":"172.16.110.129"},"message":"WebDriverAgent is ready to accept commands","state":"success","ready":true},"sessionId":null}
        2024-12-30 11:07:59:232 - [af38b09d][XCUITestDriver@f217] Event 'wdaSessionAttempted' logged at 1735556879232 (14:07:59 GMT+0300 (GMT+03:00))
        2024-12-30 11:07:59:232 - [af38b09d][XCUITestDriver@f217] Sending createSession command to WDA
2024-12-30 11:07:59:233 - [af38b09d][XCUITestDriver@f217] Matched '/session' to command name 'createSession'
        2024-12-30 11:07:59:233 - [af38b09d][XCUITestDriver@f217] Proxying [POST /session] to [POST http://127.0.0.1:8100/session] with body: {"capabilities":{"firstMatch":[{"bundleId":"--","arguments":[],"environment":{},"eventloopIdleDelaySec":0,"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true,"shouldTerminateApp":true,"forceAppLaunch":true,"useNativeCachingStrategy":true,"forceSimulatorSoftwareKeyboardPresence":false}],"alwaysMatch":{}}}
        2024-12-30 11:07:59:444 - [af38b09d][FlutterDriver@573f] Matched the syslog line 'Dec 30 14:07:59 Berkins-iPhone-15 Runner(Flutter)[10084] <Notice>: flutter: The Dart VM service is listening on http://127.0.0.1:64029/aZlk2mLu0Ss=/'
        2024-12-30 11:07:59:588 - [af38b09d][XCUITestDriver@f217] Parsed BUILD_DIR configuration value: '/Users/berkinmecik/node_modules/appium-flutter-driver/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/build'
        2024-12-30 11:07:59:588 - [af38b09d][XCUITestDriver@f217] Got derived data root: '/Users/berkinmecik/node_modules/appium-flutter-driver/node_modules/appium-xcuitest-driver/node_modules'
        2024-12-30 11:08:00:614 - [af38b09d][XCUITestDriver@f217] Got response with status 200: {"value":{"sessionId":"5BBA3D43-3030-420B-B1DB-18FA85CC521C","capabilities":{"sdkVersion":"18.1.1","device":"iphone"}},"sessionId":"5BBA3D43-3030-420B-B1DB-18FA85CC521C"}
        2024-12-30 11:08:00:615 - [af38b09d][XCUITestDriver@f217] Determined the downstream protocol as 'W3C'
        2024-12-30 11:08:00:615 - [af38b09d][XCUITestDriver@f217] WDA session startup took 1383ms
2024-12-30 11:08:00:615 - [af38b09d][XCUITestDriver@f217] Event 'wdaSessionStarted' logged at 1735556880615 (14:08:00 GMT+0300 (GMT+03:00))
        2024-12-30 11:08:00:616 - [af38b09d][XCUITestDriver@f217] Event 'wdaStarted' logged at 1735556880616 (14:08:00 GMT+0300 (GMT+03:00))
        2024-12-30 11:08:00:617 - [af38b09d][BaseDriver] The value of 'elementResponseAttributes' setting did not change. Skipping the update for it
2024-12-30 11:08:00:617 - [af38b09d][BaseDriver] The value of 'shouldUseCompactResponses' setting did not change. Skipping the update for it
2024-12-30 11:08:00:618 - [af38b09d][FlutterDriver@573f] Running on iOS real device
2024-12-30 11:08:00:622 - [af38b09d][FlutterDriver@573f] Forwarding the remote port 64029 to the local port 64029
        2024-12-30 11:08:00:623 - [af38b09d][FlutterDriver@573f] Establishing a connection to the Dart Observatory
2024-12-30 11:08:00:641 - [af38b09d][FlutterDriver@573f] Connecting to Dart Observatory: ws://127.0.0.1:64029/aZlk2mLu0Ss=/ws
        2024-12-30 11:08:00:644 - [af38b09d][FlutterDriver@573f] Listing all isolates: [{"type":"@Isolate","id":"isolates/5919571379973687","name":"main","number":"5919571379973687","isSystemIsolate":false,"isolateGroupId":"isolateGroups/7445464599630733"}]
        2024-12-30 11:08:00:656 - [af38b09d][AppiumDriver@44ac] New FlutterDriver session created successfully, session b22392a9-a9d7-4a6a-8401-11ef3e6c9082 added to master session list
2024-12-30 11:08:00:657 - [af38b09d][AppiumDriver@44ac] Event 'newSessionStarted' logged at 1735556880656 (14:08:00 GMT+0300 (GMT+03:00))
        2024-12-30 11:08:00:657 - [af38b09d][FlutterDriver@573f] Cached the protocol value 'W3C' for the new session b22392a9-a9d7-4a6a-8401-11ef3e6c9082
2024-12-30 11:08:00:657 - [af38b09d][FlutterDriver@573f] Responding to client with driver.createSession() result: {"capabilities":{"subcommand":"server","address":"127.0.0.1","logFile":"appium.log","logTimestamp":true,"port":4728,"extraArgs":[],"allowCors":false,"allowInsecure":[],"basePath":"","callbackPort":4723,"debugLogSpacing":false,"denyInsecure":[],"keepAliveTimeout":600,"localTimezone":false,"loglevel":"debug","logFormat":"text","logNoColors":false,"pluginsImportChunkSize":7,"driversImportChunkSize":3,"longStacktrace":false,"noPermsCheck":false,"relaxedSecurityEnabled":false,"shutdownTimeout":5000,"sessionOverride":false,"strictCaps":false,"useDrivers":[],"usePlugins":[],"driver":{"xcuitest":{"wdaLocalPort":8100}},"tmpDir":"/var/folders/7z/v1dbyxp966jcs0p5pmmsv0nh0000gn/T","platformName":"iOS","platformVersion":"18.1.1","udid":"--","automationName":"Flutter","xcodeOrgId":"--","xcodeSigningId":"iPhone Developer","bundleId":"--","showXcodeLog":true,"includeSafariInWebviews":true,"newCommandTimeout":3600,"connectHardwareKeyboard":true,"fastReset":true,"skipUninstal...
        2024-12-30 11:08:00:660 - [af38b09d][HTTP] <-- POST /session 200 1833 ms - 1091
        2024-12-30 11:08:00:705 - [b22392a9][HTTP] --> GET /session/b22392a9-a9d7-4a6a-8401-11ef3e6c9082/appium/settings {}
2024-12-30 11:08:00:710 - [b22392a9][FlutterDriver@573f] Calling AppiumDriver.getSettings() with args: ["b22392a9-a9d7-4a6a-8401-11ef3e6c9082"]
        2024-12-30 11:08:00:711 - [b22392a9][FlutterDriver] Executing Flutter driver command 'getSettings'
        2024-12-30 11:08:00:712 - [b22392a9][FlutterDriver@573f] Responding to client with driver.getSettings() result: {}
        2024-12-30 11:08:00:713 - [b22392a9][HTTP] <-- GET /session/b22392a9-a9d7-4a6a-8401-11ef3e6c9082/appium/settings 200 7 ms - 12
        2024-12-30 11:08:01:204 - [b22392a9][HTTP] --> GET /session/b22392a9-a9d7-4a6a-8401-11ef3e6c9082/screenshot {}
2024-12-30 11:08:01:205 - [b22392a9][FlutterDriver@573f] Calling AppiumDriver.getScreenshot() with args: ["b22392a9-a9d7-4a6a-8401-11ef3e6c9082"]
        2024-12-30 11:08:01:205 - [b22392a9][FlutterDriver] Executing Flutter driver command 'getScreenshot'
        2024-12-30 11:08:01:210 - [b22392a9][FlutterDriver@573f] [ '{"code":-32000,"message":"Could not capture image screenshot."}' ]
        2024-12-30 11:08:01:216 - [b22392a9][FlutterDriver@573f] Encountered internal error running command: Error: {"code":-32000,"message":"Could not capture image screenshot."}
at Object.errorWithException (/Users/berkinmecik/node_modules/@appium/support/lib/logging.js:41:45)
at Object.errorAndThrow (/Users/berkinmecik/node_modules/@appium/support/lib/logging.js:44:18)
at IsolateSocket.socket.call (/Users/berkinmecik/node_modules/appium-flutter-driver/lib/sessions/observatory.ts:64:20)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at FlutterDriver.getScreenshot (/Users/berkinmecik/node_modules/appium-flutter-driver/lib/commands/screen.ts:4:20)
2024-12-30 11:08:01:227 - [b22392a9][HTTP] <-- GET /session/b22392a9-a9d7-4a6a-8401-11ef3e6c9082/screenshot 500 23 ms - 644
        2024-12-30 11:08:01:232 - [b22392a9][HTTP] --> GET /session/b22392a9-a9d7-4a6a-8401-11ef3e6c9082/window/rect {}
2024-12-30 11:08:01:237 - [b22392a9][FlutterDriver@573f] Calling AppiumDriver.getWindowRect() with args: ["b22392a9-a9d7-4a6a-8401-11ef3e6c9082"]
        2024-12-30 11:08:01:237 - [b22392a9][FlutterDriver] Executing Flutter driver command 'getWindowRect'
        2024-12-30 11:08:01:244 - [b22392a9][FlutterDriver@573f] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
at FlutterDriver.executeCommand (/Users/berkinmecik/node_modules/@appium/base-driver/lib/basedriver/driver.ts:101:13)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at FlutterDriver.executeCommand (/Users/berkinmecik/node_modules/appium-flutter-driver/lib/driver.ts:224:16)
at defaultBehavior (/opt/homebrew/lib/node_modules/appium/lib/appium.js:1136:14)
at AppiumDriver.executeWrappedCommand (/opt/homebrew/lib/node_modules/appium/lib/appium.js:1242:16)
at AppiumDriver.executeCommand (/opt/homebrew/lib/node_modules/appium/lib/appium.js:1148:17)
at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:387:19)
2024-12-30 11:08:01:244 - [b22392a9][HTTP] <-- GET /session/b22392a9-a9d7-4a6a-8401-11ef3e6c9082/window/rect 405 12 ms - 886
        2024-12-30 11:08:01:249 - [b22392a9][HTTP] --> GET /session/b22392a9-a9d7-4a6a-8401-11ef3e6c9082/source {}
2024-12-30 11:08:01:249 - [b22392a9][FlutterDriver@573f] Calling AppiumDriver.getPageSource() with args: ["b22392a9-a9d7-4a6a-8401-11ef3e6c9082"]
        2024-12-30 11:08:01:249 - [b22392a9][FlutterDriver] Executing Flutter driver command 'getPageSource'
        2024-12-30 11:08:01:250 - [b22392a9][FlutterDriver@573f] Encountered internal error running command: NotImplementedError: Not implemented yet for find.
at FlutterDriver.getPageSource (/Users/berkinmecik/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:103:11)
at commandExecutor (/Users/berkinmecik/node_modules/@appium/base-driver/lib/basedriver/driver.ts:107:18)
at /Users/berkinmecik/node_modules/async-lock/lib/index.js:171:12
at AsyncLock._promiseTry (/Users/berkinmecik/node_modules/async-lock/lib/index.js:306:31)
at exec (/Users/berkinmecik/node_modules/async-lock/lib/index.js:170:9)
at AsyncLock.acquire (/Users/berkinmecik/node_modules/async-lock/lib/index.js:189:3)
at FlutterDriver.executeCommand (/Users/berkinmecik/node_modules/@appium/base-driver/lib/basedriver/driver.ts:123:39)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at FlutterDriver.executeCommand (/Users/berkinmecik/node_modules/appium-flutter-driver/lib/driver.ts:224:16)
at defaultBehavior (/opt/homebrew/lib/node_modules/appium/lib/appium.js:1136:14)
at AppiumDriver.executeWrappedCommand (/opt/homebrew/lib/node_modules/appium/lib/appium.js:1242:16)
at AppiumDriver.executeCommand (/opt/homebrew/lib/node_modules/appium/lib/appium.js:1148:17)
at asyncHandler (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:387:19)
2024-12-30 11:08:01:251 - [b22392a9][HTTP] <-- GET /session/b22392a9-a9d7-4a6a-8401-11ef3e6c9082/source 405 2 ms - 1443
        2024-12-30 11:08:20:707 - [b22392a9][HTTP] --> GET /session/b22392a9-a9d7-4a6a-8401-11ef3e6c9082/timeouts {}
2024-12-30 11:08:20:708 - [b22392a9][FlutterDriver@573f] Calling AppiumDriver.getTimeouts() with args: ["b22392a9-a9d7-4a6a-8401-11ef3e6c9082"]
        2024-12-30 11:08:20:709 - [b22392a9][FlutterDriver] Executing Flutter driver command 'getTimeouts'
        2024-12-30 11:08:20:710 - [b22392a9][FlutterDriver@573f] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
        2024-12-30 11:08:20:713 - [b22392a9][HTTP] <-- GET /session/b22392a9-a9d7-4a6a-8401-11ef3e6c9082/timeouts 200 4 ms - 42
        2024-12-30 11:08:40:707 - [b22392a9][HTTP] --> GET /session/b22392a9-a9d7-4a6a-8401-11ef3e6c9082/timeouts {}
2024-12-30 11:08:40:708 - [b22392a9][FlutterDriver@573f] Calling AppiumDriver.getTimeouts() with args: ["b22392a9-a9d7-4a6a-8401-11ef3e6c9082"]
        2024-12-30 11:08:40:708 - [b22392a9][FlutterDriver] Executing Flutter driver command 'getTimeouts'
        2024-12-30 11:08:40:709 - [b22392a9][FlutterDriver@573f] Responding to client with driver.getTimeouts() result: {"command":3600000,"implicit":0}
        2024-12-30 11:08:40:711 - [b22392a9][HTTP] <-- GET /session/b22392a9-a9d7-4a6a-8401-11ef3e6c9082/timeouts 304 4 ms - -
        2024-12-30 11:09:00:706 - [b22392a9][HTTP] --> GET /session/b22392a9-a9d7-4a6a-8401-11ef3e6c9082/timeouts {}
```

**Comment by mlab817** [comment]
Did you ever figure this out? I'm trying this in simulator but this just the message i am getting:

```log
[dc6b69d3][FlutterDriver] Executing Flutter driver command 'getScreenshot'
[dc6b69d3][FlutterDriver@a656] [ '{"code":-32000,"message":"Could not capture image screenshot."}' ]
[dc6b69d3][FlutterDriver@a656] Encountered internal error running command: Error: {"code":-32000,"message":"Could not capture image screenshot."}
```
